/* Generated by Together */
#include "stdafx.h"
#include <iostream>
#include <thread>
#include "GroupServerApp.h"
#include "log.h"
#include "GameCommon.h"
#include "CommFunc.h"
#include "DBConnect.h"
#include "Team.h"
#include "GuildBankMsg.h"
#include "conformity.h"
#include "PacketSanitizer.h"

using namespace std;

LoginManageList::LoginManageList() {
	InitializeCriticalSection(&m_cs);
}

LoginManageList::~LoginManageList() {
	DeleteCriticalSection(&m_cs);
}

bool LoginManageList::Insert(const std::string& name) {
	bool ret = false;
	Lock();
	if (!_Query(name)) {
		m_list.push_back(name);
		ret = true;
	}
	UnLock();
	return ret;
}

bool LoginManageList::Remove(const std::string& name) {
	bool ret = false;
	LoginNameList::iterator it;
	Lock();
	for (it = m_list.begin(); it != m_list.end(); it++) {
		if ((*it) == name) {
			ret = true;
			m_list.erase(it);
			break;
		}
	}
	UnLock();
	return ret;
}

bool LoginManageList::Query(const std::string& name) {
	bool ret = false;
	Lock();

	ret = _Query(name);

	UnLock();
	return ret;
}

bool LoginManageList::_Query(const std::string& name) {
	bool ret = false;
	LoginNameList::iterator it;

	for (it = m_list.begin(); it != m_list.end(); it++) {
		if ((*it) == name) {
			ret = true;
			break;
		}
	}

	return ret;
}

void LoginManageList::Lock() {
	EnterCriticalSection(&m_cs);
}

void LoginManageList::UnLock() {
	LeaveCriticalSection(&m_cs);
}

// =====================================================
// Player Pointer Validation System Implementation
// =====================================================

void GroupServerApp::RegisterPlayer(Player* ply) {
	if (!ply) return;
	
	std::unique_lock<std::shared_mutex> lock(m_playerRegistryMutex);
	uintptr_t ptr = reinterpret_cast<uintptr_t>(ply);
	m_playerRegistry[ptr] = ply->m_generation;
	
	LG("Security", "RegisterPlayer: ptr=0x%llX gen=%u total=%zu\n", 
	   static_cast<unsigned long long>(ptr), ply->m_generation, m_playerRegistry.size());
}

void GroupServerApp::UnregisterPlayer(Player* ply) {
	if (!ply) return;
	
	std::unique_lock<std::shared_mutex> lock(m_playerRegistryMutex);
	uintptr_t ptr = reinterpret_cast<uintptr_t>(ply);
	
	auto it = m_playerRegistry.find(ptr);
	if (it != m_playerRegistry.end()) {
		LG("Security", "UnregisterPlayer: ptr=0x%llX gen=%u remaining=%zu\n",
		   static_cast<unsigned long long>(ptr), ply->m_generation, m_playerRegistry.size() - 1);
		m_playerRegistry.erase(it);
	}
}

Player* GroupServerApp::ValidatePlayerPointer(uintptr_t ptr, uint64_t expectedGtAddr, uint32_t generation) {
	if (ptr == 0) {
		return nullptr;
	}
	
	// First check if the pointer is in our registry
	{
		std::shared_lock<std::shared_mutex> lock(m_playerRegistryMutex);
		auto it = m_playerRegistry.find(ptr);
		if (it == m_playerRegistry.end()) {
			// Pointer not registered - definitely invalid
			LG("Security", "ValidatePlayerPointer: REJECTED unregistered ptr=0x%llX\n",
			   static_cast<unsigned long long>(ptr));
			return nullptr;
		}
		
		// If generation was provided, verify it matches
		if (generation != 0 && it->second != generation) {
			LG("Security", "ValidatePlayerPointer: REJECTED stale ptr=0x%llX expected_gen=%u actual_gen=%u\n",
			   static_cast<unsigned long long>(ptr), generation, it->second);
			return nullptr;
		}
	}
	
	// Pointer is registered, now safely access the player
	Player* ply = reinterpret_cast<Player*>(ptr);
	
	try {
		// Verify the GateServer address matches
		if (ply->m_gtAddr != expectedGtAddr) {
			LG("Security", "ValidatePlayerPointer: REJECTED gtAddr mismatch ptr=0x%llX expected=%llu actual=%llu\n",
			   static_cast<unsigned long long>(ptr), expectedGtAddr, ply->m_gtAddr);
			return nullptr;
		}
		
		// Additional sanity check: player should have a valid gate
		if (!ply->m_gate) {
			LG("Security", "ValidatePlayerPointer: REJECTED no gate ptr=0x%llX\n",
			   static_cast<unsigned long long>(ptr));
			return nullptr;
		}
		
		return ply;
	} catch (...) {
		LG("Security", "ValidatePlayerPointer: EXCEPTION accessing ptr=0x%llX\n",
		   static_cast<unsigned long long>(ptr));
		return nullptr;
	}
}

bool GroupServerApp::IsPlayerRegistered(Player* ply) {
	if (!ply) return false;
	
	std::shared_lock<std::shared_mutex> lock(m_playerRegistryMutex);
	uintptr_t ptr = reinterpret_cast<uintptr_t>(ply);
	return m_playerRegistry.find(ptr) != m_playerRegistry.end();
}

bool GroupServerApp::OnConnect(DataSocket* datasock) // Connection callback: true=accept, false=reject
{
	const char* peerIP = datasock->GetPeerIP();
	int peerPort = datasock->GetPeerPort();
	
	// Check IP whitelist FIRST before doing anything else
	if (!IsIPAllowed(peerIP)) {
		if (m_security.logRejected) {
			LG("Security", "[Security] REJECTED connection from unauthorized IP: %s:%d\n", peerIP, peerPort);
			std::cout << "[Security] REJECTED connection from unauthorized IP: " << peerIP << ":" << peerPort << std::endl;
		}
		return false; // Reject connection immediately
	}
	
	datasock->SetRecvBuf(64 * 1024);
	datasock->SetSendBuf(64 * 1024);
	if (!datasock->IsServer()) {
		LG("Connect", "AccountServer:%s,%d come ! Socket num:%d\n", peerIP, peerPort, GetSockTotal() + 1);
		std::cout << "AccountServer:" << peerIP << "," << peerPort << "come ! Socket num:" << GetSockTotal() + 1 << std::endl;
	} else {
		LG("Connect", "GateServer:%s,%d come ! Socket num:%d\n", peerIP, peerPort, GetSockTotal() + 1);
		std::cout << "GateServer:" << peerIP << "," << peerPort << "come ! Socket num:" << GetSockTotal() + 1 << std::endl;
	}
	return true;
}

void GroupServerApp::OnDisconnect(DataSocket* datasock, int reason) {
	if (!datasock->IsServer()) {
		m_mtxlogin.lock();
		try {
			if (g_gpsvr->m_acctsock == datasock) {
				g_gpsvr->m_acctsock = 0;
			}
		} catch (...) {
		}
		m_mtxlogin.unlock();
		LG("Connect", "AccountServer:%s,%d go ! Socket num:%d reason=(%d)%s\n",
		   datasock->GetPeerIP(), datasock->GetPeerPort(), GetSockTotal(), reason, GetDisconnectErrText(reason).c_str());
		// std::cout<<"AccountServer:"<<datasock->GetPeerIP()<<","<<datasock->GetPeerPort()<<"�?�???Socket�y:"<<GetSockTotal()<<"reason="<<GetDisconnectErrText(reason).c_str()<<std::endl;
		std::cout << "AccountServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "go ! Socket num:" << GetSockTotal() << "reason=" << GetDisconnectErrText(reason).c_str() << std::endl;

		if (reason == DS_SHUTDOWN || reason == DS_DISCONN) {
			return;
		}

		// Reconnect to AccountServer in a detached background thread so we don't
		// block a processor thread (which would starve RPC handling from GateServer).
		std::thread([&gpapp = *g_gpsvr]() {
			std::cout << "after 5 seconds reconnect AccountServer......" << std::endl;
			Sleep(5000);
			InitACTSvrConnect(const_cast<GroupServerApp&>(gpapp));
		}).detach();
	} else {
		GateServer* l_gate = (GateServer*)datasock->GetPointer();
		if (!l_gate) {
			return;
		}
		m_mtxlogin.lock();
		try {
			l_gate->SetDataSock(0);
		} catch (...) {
		}
		m_mtxlogin.unlock();
		LG("Connect", "GateServer:%s,%d go ! Socket num:%d reason=(%d)%s\n",
		   datasock->GetPeerIP(), datasock->GetPeerPort(), GetSockTotal(), reason, GetDisconnectErrText(reason).c_str());
		// std::cout<<"GateServer:"<<datasock->GetPeerIP()<<","<<datasock->GetPeerPort()<<"�?�???Socket�y:"<<GetSockTotal()<<"reason="<<GetDisconnectErrText(reason).c_str()<<std::endl;
		std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "go ! Socket num:" << GetSockTotal() << "reason=" << GetDisconnectErrText(reason).c_str() << std::endl;

		Player* l_ply = 0;
		RunChainGetArmor<Player> l(m_plylst);
		while (l_ply = m_plylst.GetNextItem()) {
			if (l_ply->m_gate == l_gate) {
				RPacket l_rpk;
				TP_USER_LOGOUT(l_ply, datasock, l_rpk);
			}
		}
		l.unlock();
	}
}

WPacket GroupServerApp::OnServeCall(DataSocket* datasock, RPacket& pk) {
	uShort l_cmd = pk.ReadCmd();

	// Validate CMD is within a valid range for GroupServer SyncCalls
	// Valid ranges: CMD_TP (2000-2050), CMD_OS (6500-6550)
	bool validCmd =
		(l_cmd >= CMD_TP_BASE && l_cmd <= CMD_TP_BASE + 50) ||
		(l_cmd >= CMD_OS_BASE && l_cmd <= CMD_OS_BASE + 50);

	if (!validCmd) {
		LG("Security", "[PacketValidation] Invalid CMD %u from %s:%d in OnServeCall - rejected\n",
		   static_cast<unsigned int>(l_cmd), datasock->GetPeerIP(), datasock->GetPeerPort());
		WPacket l_retpk = GetWPacket();
		l_retpk.WriteShort(ERR_PT_LOGFAIL);
		return l_retpk;
	}

	switch (l_cmd) {
	case CMD_TP_LOGIN:
		return TP_LOGIN(datasock, pk);
	case CMD_TP_USER_LOGIN:
		return TP_USER_LOGIN(datasock, pk);
	case CMD_TP_REQPLYLST:
		return TP_REQPLYLST(datasock, pk);
		// Add by lark.li 20081119 begin
	case CMD_TP_SYNC_PLYLST:
		return TP_SYNC_PLYLST(datasock, pk);
	case CMD_OS_LOGIN:
		return OS_LOGIN(datasock, pk);
		// End
	case CMD_TP_REGISTER:
		return TP_REGISTER(datasock, pk);
	}

	// Read player pointer and gate address from packet
	uintptr_t l_plyptr = static_cast<uintptr_t>(pk.ReverseReadLongLong());
	unsigned long long l_gtaddr = pk.ReverseReadLongLong();
	
	// Use safe validation system to get player pointer
	Player* l_ply = ValidatePlayerPointer(l_plyptr, l_gtaddr);
	
	if (!l_ply) {
		// Player pointer is invalid (stale, unregistered, or mismatched)
		LG("Security", "OnServeCall CMD %d: Invalid player pointer 0x%llX from %s\n",
		   l_cmd, static_cast<unsigned long long>(l_plyptr), datasock->GetPeerIP());
		WPacket l_retpk = GetWPacket();
		l_retpk.WriteShort(ERR_PT_KICKUSER);
		return l_retpk;
	}
	
	switch (l_cmd) {

	case CMD_TP_USER_LOGOUT:
		return TP_USER_LOGOUT(l_ply, datasock, pk);
	case CMD_TP_BGNPLAY:
		return TP_BGNPLAY(l_ply, datasock, pk);
	case CMD_TP_ENDPLAY:
		return TP_ENDPLAY(l_ply, datasock, pk);
	case CMD_TP_NEWCHA:
		return TP_NEWCHA(l_ply, datasock, pk);
	case CMD_TP_DELCHA:
		return TP_DELCHA(l_ply, datasock, pk);
	case CMD_TP_CREATE_PASSWORD2:
		return TP_CREATE_PASSWORD2(l_ply, datasock, pk);
	case CMD_TP_UPDATE_PASSWORD2:
		return TP_UPDATE_PASSWORD2(l_ply, datasock, pk);
	case CMD_TP_CHANGEPASS:
		return TP_CHANGEPASS(l_ply, datasock, pk);
	}
	return 0;
}

// change password function >>>client << mothannakh >>add cooldown<<//
WPacket GroupServerApp::TP_CHANGEPASS(Player* l_ply, DataSocket* datasock, RPacket& pk) {
	cChar* newPass = pk.ReadString();
	cChar* PIN = pk.ReadString();
	WPacket l_wpk = GetWPacket();
	l_wpk.WriteCmd(CMD_PC_ERRMSG);

	if (!newPass || !PIN) {
		l_wpk.WriteString("Invalid request.");
		return l_wpk;
	}
	if (!PS::IsSafeString(newPass)) {
		LG("Security", "[GroupServer] TP_CHANGEPASS: unsafe characters in new password from account '%s'\n", l_ply->m_acctname.c_str());
		l_wpk.WriteString("Invalid Password.");
		return l_wpk;
	}
	if (strcmp(l_ply->m_password.c_str(), PIN) != 0) {
		l_wpk.WriteString("Incorrect PIN.");
	} else if (strlen(newPass) != 32 || !isAlphaNumeric(newPass, strlen(newPass))) {
		l_wpk.WriteString("Invalid Password.");
	} else {
		WPacket l_wpk_acc = GetWPacket();
		l_wpk_acc.WriteCmd(CMD_PA_CHANGEPASS);
		l_wpk_acc.WriteString(l_ply->m_acctname.c_str());
		l_wpk_acc.WriteString(newPass);
		g_gpsvr->SendData(g_gpsvr->m_acctsock, l_wpk_acc);

		l_wpk.WriteString("Password has been changed.");
	}
	return l_wpk;
}
// this form already has cooldown inside client  , maybe add second one here?
WPacket GroupServerApp::TP_REGISTER(DataSocket* datasock, RPacket& pk) {
	cChar* userName = pk.ReadString();
	cChar* password = pk.ReadString();

	cChar* email = pk.ReadString();

	int len = strlen(userName);
	int passlen = strlen(password);
	int emaillen = strlen(email);
	WPacket ret_pk = g_gpsvr->GetWPacket();
	ret_pk.WriteCmd(CMD_PT_REGISTER);

	// SANITIZE: Check for dangerous characters in all fields
	if (!PS::ValidateUsername(userName)) {
		LG("Security", "[Register] Invalid username characters: %s\n", userName);
		ret_pk.WriteChar(0);
		ret_pk.WriteString("Invalid Username (contains forbidden characters).");
	} else if (!PS::IsSafeString(password)) {
		LG("Security", "[Register] Invalid password characters from: %s\n", userName);
		ret_pk.WriteChar(0);
		ret_pk.WriteString("Invalid Password (contains forbidden characters).");
	} else if (!PS::IsSafeString(email)) {
		LG("Security", "[Register] Invalid email characters from: %s\n", userName);
		ret_pk.WriteChar(0);
		ret_pk.WriteString("Invalid Email (contains forbidden characters).");
	} else if (len < 5 || len > 16 || !isAlphaNumeric(userName, len)) {
		ret_pk.WriteChar(0);
		ret_pk.WriteString("Invalid Username.");
	} else if (passlen < 5 || passlen > 32) {
		// Accept plaintext password (5-32 chars) - AccountServer will hash with bcrypt
		ret_pk.WriteChar(0);
		ret_pk.WriteString("Invalid Password (5-32 characters required).");
	} else if (emaillen < 3 || emaillen > 254 || !isEmail(email)) {
		ret_pk.WriteChar(0);
		ret_pk.WriteString("Invalid Email.");
	} else {
		auto db = GetDB();
		if (!db) {
			ret_pk.WriteChar(0);
			ret_pk.WriteString("Server busy, try again.");
		} else if (db->tblaccounts->FetchRowByActName(userName)) {
			ret_pk.WriteChar(0);
			ret_pk.WriteString("Username is taken.");
		} else if (db->tblaccounts->InsertRow(0, userName, "0")) {
			// request acc server to insert other half.
			WPacket l_wpk = g_gpsvr->GetWPacket();
			l_wpk.WriteCmd(CMD_PA_REGISTER);
			l_wpk.WriteString(userName);
			l_wpk.WriteString(password);
			l_wpk.WriteString(email);
			g_gpsvr->SendData(g_gpsvr->m_acctsock, l_wpk);
			// tell client acc created.
			ret_pk.WriteChar(1);
		} else {
			ret_pk.WriteChar(0);
			ret_pk.WriteString("Unknown Error.");
		}
	}
	return ret_pk;
}
void GroupServerApp::OnProcessData(DataSocket* datasock, RPacket& recvbuf) {
	try {
		uShort l_cmd = recvbuf.ReadCmd();

		// Validate CMD is within a valid range for GroupServer
		// Valid ranges: CMD_TP (2000-2050), CMD_AP (3500-3550), CMD_MP (5500-5550), CMD_CP (6000-6500)
		bool validCmd =
			(l_cmd >= CMD_TP_BASE && l_cmd <= CMD_TP_BASE + 50) ||
			(l_cmd >= CMD_AP_BASE && l_cmd <= CMD_AP_BASE + 50) ||
			(l_cmd >= CMD_MP_BASE && l_cmd <= CMD_MP_BASE + 50) ||
			(l_cmd >= CMD_CP_BASE && l_cmd <= CMD_CP_BASE + 500);

		if (!validCmd) {
			LG("Security", "[PacketValidation] Invalid CMD %u from %s:%d in OnProcessData - rejected\n",
			   static_cast<unsigned int>(l_cmd), datasock->GetPeerIP(), datasock->GetPeerPort());
			return;
		}

#ifdef _DEBUG
		LG("OnProcessData", "CMD: %d\n", l_cmd);
#endif
		switch (l_cmd) {
		case CMD_AP_KICKUSER:
			recvbuf.ReadShort();
			AP_KICKUSER(datasock, recvbuf);
			return;
		case CMD_AP_EXPSCALE: //  ��3�??
			AP_EXPSCALE(datasock, recvbuf);
			return;
		case CMD_TP_DISC:
			TP_DISC(datasock, recvbuf);
			return;
		case CMD_TP_ESTOPUSER_CHECK:
			TP_ESTOPUSER_CHECK(datasock, recvbuf);
			return;
		case CMD_MP_GUILD_CHALL_PRIZEMONEY:
			MP_GUILD_CHALL_PRIZEMONEY(nullptr, datasock, recvbuf);
			return;
		case CMD_MP_GM1SAY1: // Add by sunny.sun 20080804
			CP_GM1SAY1(nullptr, datasock, recvbuf);
			return;
		case CMD_MP_GM1SAY:
			CP_GM1SAY(nullptr, datasock, recvbuf);
			return;
		case CMD_MP_GMBANACCOUNT:
			MP_GM_BANACCOUNT(nullptr, datasock, recvbuf);
			return;
		case CMD_MP_GMUNBANACCOUNT:
			MP_GM_UNBANACCOUNT(nullptr, datasock, recvbuf);
			return;
		case CMD_MP_GUILDNOTICE:
			MP_GUILDNOTICE(nullptr, datasock, recvbuf);
			return;
		case CMD_MP_CANRECEIVEREQUESTS:
			MP_CANRECEIVEREQUESTS(datasock, recvbuf);
			return;
		default:
			break; // Fall through to player-specific command handling below
		}

		// Read player pointer and gate address from packet
		uintptr_t l_plyptr = static_cast<uintptr_t>(recvbuf.ReverseReadLongLong());
		unsigned long long l_gtaddr = recvbuf.ReverseReadLongLong();
		
		// Use safe validation system to get player pointer
		// This checks: 1) pointer is registered, 2) generation matches, 3) gtAddr matches, 4) has valid gate
		Player* l_ply = ValidatePlayerPointer(l_plyptr, l_gtaddr);
		
		if (!l_ply) {
			// Player pointer is invalid (stale, unregistered, or mismatched)
			// For CMD_MP_ENTERMAP, this could be a race condition - log but don't kick aggressively
			if (l_cmd == CMD_MP_ENTERMAP) {
				LG("Security", "CMD_MP_ENTERMAP: Invalid player pointer 0x%llX from %s (possible race condition)\n",
				   static_cast<unsigned long long>(l_plyptr), datasock->GetPeerIP());
			} else {
				KickUser(datasock, l_plyptr, l_gtaddr);
			}
			return;
		}
		
		// Additional check for non-ENTERMAP commands: player must have selected a character
		if (l_cmd != CMD_MP_ENTERMAP && l_ply->m_currcha < 0) {
			KickUser(datasock, l_plyptr, l_gtaddr);
			return;
		}
		
		switch (l_cmd) {
		case CMD_MP_PUSHTOGUILDBANK:
		case CMD_CP_GUILDBANK: {
			int guildID = l_ply->m_guild[l_ply->m_currcha];
			if (guildID < 1 || guildID > MAX_GUILD_ID) {
				WPacket l_wpk = GetWPacket();
				l_wpk.WriteCmd(CMD_PC_ERRMSG);
				l_wpk.WriteString("Invalid guild. Please contact support.");
				SendToClient(l_ply, l_wpk);
				return;
			}

			WPacket l_wpk = WPacket(recvbuf).Duplicate();
			if (l_cmd == CMD_CP_GUILDBANK) {
				l_wpk.WriteCmd(CMD_PM_GUILDBANK);
			} else if (l_cmd == CMD_MP_PUSHTOGUILDBANK) {
				l_wpk.WriteCmd(CMD_PM_PUSHTOGUILDBANK);
			}

			GuildBankMsg gbm;
			gbm.player = l_ply;
			gbm.msg = l_wpk;
			gbm.playerChaID = l_ply->m_chaid[l_ply->m_currcha];  // Store for validation

			const int queueSize = guildBankMsgQueue[guildID].size();

			if (queueSize >= 10) {
				WPacket l_wpk = GetWPacket();
				l_wpk.WriteCmd(CMD_PC_ERRMSG);
				l_wpk.WriteString("Guild Bank is currently busy. Try again later.");
				SendToClient(l_ply, l_wpk);
				return;
			}

			guildBankMsgQueue[guildID].push_back(gbm);
			SendToClient(l_ply, l_wpk);

			break;
		}

		case CMD_MP_GUILDBANK: {
			int guildID = recvbuf.ReadLong();

			if (guildID < 1 || guildID > MAX_GUILD_ID) {
				return;
			}

			auto& msgQueue = guildBankMsgQueue[guildID];
			if (!msgQueue.empty()) {
				// Pop previous(processed) request
				msgQueue.pop_front();

				// Send next request in queue if any
				while (!msgQueue.empty()) {
					auto& msg = msgQueue.front();
					// Validate player is still connected and valid
					if (msg.player && msg.player->m_currcha >= 0 && 
					    msg.player->m_chaid[msg.player->m_currcha] == msg.playerChaID) {
						SendToClient(msg.player, msg.msg);
						break;
					} else {
						// Player disconnected or invalid, skip this request
						msgQueue.pop_front();
					}
				}
			}
			break;
		}

		case CMD_MP_GUILD_PERM: {
			int targetID = recvbuf.ReadLong();
			unsigned int permission = recvbuf.ReadLong();

			Guild* l_guild = l_ply->GetGuild();
			if (!l_guild) {
				return;
			}
			Player* l_dst = l_guild->FindGuildMemByChaID(targetID);
			// update in memory if player is online
			if (l_dst && l_dst->m_currcha >= 0) {
				l_dst->m_guildPermission[l_dst->m_currcha] = permission;
			}
			// if player is on char select screen, find desired char and update
			// else if (l_dst){
			//	for (int i = 0; i < 10; i++){
			//		if (l_dst->m_chaid[i] == targetID){
			//			l_dst->m_guildPermission[i] = permission;
			//			break;
			//		}
			//	}
			// }
			// notify all in guild that permission has changed.
			WPacket l_wpk = GetWPacket();
			l_wpk.WriteCmd(CMD_PC_GUILD_PERM);
			l_wpk.WriteLong(targetID);
			l_wpk.WriteLong(permission);

			Player* l_plylst[10240];
			short l_plynum = 0;

			RunChainGetArmor<GuildMember> l(*l_guild);
			while (l_ply = static_cast<Player*>(l_guild->GetNextItem())) {
				l_plylst[l_plynum] = l_ply;
				l_plynum++;
			}
			l.unlock();

			SendToClient(l_plylst, l_plynum, l_wpk);
			return;
		}
		case CMD_CP_PING:
			CP_PING(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_REPORT_WG:
			CP_REPORT_WG(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GUILD_MOTTO:
			MP_GUILD_MOTTO(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GUILD_CHALLMONEY:
			MP_GUILD_CHALLMONEY(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GUILD_DISBAND:
			MP_GUILD_DISBAND(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GUILD_LEAVE:
			MP_GUILD_LEAVE(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GUILD_KICK:
			MP_GUILD_KICK(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GUILD_CREATE:
			MP_GUILD_CREATE(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GUILD_APPROVE:
			MP_GUILD_APPROVE(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_SAY2ALL:
			MP_SAY2ALL(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_SAY2TRADE:
			MP_SAY2TRADE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_REFUSETOME:
			CP_REFUSETOME(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_GM1SAY:
			CP_GM1SAY(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_GM1SAY1: // Add by sunny.sun 20080804
			CP_GM1SAY1(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SAY2TRADE:
			CP_SAY2TRADE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SAY2ALL:
			CP_SAY2ALL(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SAY2YOU:
			CP_SAY2YOU(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SAY2TEM:
			CP_SAY2TEM(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SAY2GUD:
			CP_SAY2GUD(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_TEAM_INVITE:
			CP_TEAM_INVITE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_TEAM_ACCEPT:
			CP_TEAM_ACCEPT(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_TEAM_REFUSE:
			CP_TEAM_REFUSE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_TEAM_LEAVE:
			CP_TEAM_LEAVE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_TEAM_KICK:
			CP_TEAM_KICK(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_TEAM_CREATE:
			MP_TEAM_CREATE(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_ENTERMAP:
			MP_ENTERMAP(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_MASTER_CREATE:
			MP_MASTER_CREATE(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_MASTER_DEL:
			MP_MASTER_DEL(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_MASTER_FINISH:
			MP_MASTER_FINISH(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_MASTER_REFRESH_INFO:
			CP_MASTER_REFRESH_INFO(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_PRENTICE_REFRESH_INFO:
			CP_PRENTICE_REFRESH_INFO(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_FRND_INVITE:
			CP_FRND_INVITE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_FRND_ACCEPT:
			CP_FRND_ACCEPT(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_FRND_REFUSE:
			CP_FRND_REFUSE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_FRND_DELETE:
			CP_FRND_DELETE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_FRND_CHANGE_GROUP:
			CP_FRND_CHANGE_GROUP(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_FRND_REFRESH_INFO:
			CP_FRND_REFRESH_INFO(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_CHANGE_PERSONINFO:
			CP_CHANGE_PERSONINFO(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SESS_CREATE:
			CP_SESS_CREATE(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SESS_SAY:
			CP_SESS_SAY(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SESS_ADD:
			CP_SESS_ADD(l_ply, datasock, recvbuf);
			return;
		case CMD_CP_SESS_LEAVE:
			CP_SESS_LEAVE(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GARNER2_CGETORDER:
			CP_GARNER2_GETORDER(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_GARNER2_UPDATE: // �'?����????�D?�?D?�?????
			MP_GARNER2_UPDATE(l_ply, datasock, recvbuf);
			return;
		case CMD_MP_MUTE_PLAYER:
			MP_MUTE_PLAYER(l_ply, datasock, recvbuf);
			return;
		default:
			LG("Security", "[PacketValidation] Unhandled CMD %u from %s:%d in OnProcessData (player switch)\n",
			   static_cast<unsigned int>(l_cmd), datasock->GetPeerIP(), datasock->GetPeerPort());
			return;
		}
	} catch (...) {
		LG("packetException", "Packet exception from [%s:%d] in OnProcessData\n",
		   datasock->GetPeerIP(), datasock->GetPeerPort());
		return;
	}
}

// Add by lark.li 20081119 begin
WPacket GroupServerApp::TP_SYNC_PLYLST(DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();

	m_mtxSyn.lock();

	try {
		uLong num = pk.ReadLong();
		cChar* l_gatename = pk.ReadString();
		GateServer* pServer = this->FindGateSByName(l_gatename);

		if (pServer) {
			l_retpk.WriteShort(ERR_SUCCESS);

			l_retpk.WriteShort((uShort)num);
			for (int i = 0; i < (int)num; i++) {
				Player* l_ply = g_gpsvr->m_plyheap.Get();
				if (l_ply) {
					// Register player in validation registry immediately after allocation
					g_gpsvr->RegisterPlayer(l_ply);
					
					l_retpk.WriteShort(1);
					l_retpk.WriteLongLong(reinterpret_cast<uintptr_t>(l_ply));

					l_ply->m_gate = pServer;
					l_ply->m_gtAddr = pk.ReverseReadLongLong();
					l_ply->m_acctLoginID = pk.ReadLong();
					l_ply->m_acctid = pk.ReadLong();

					l_ply->BeginRun();
				} else {
					l_retpk.WriteShort(0);
				}
			}
		} else
			l_retpk.WriteShort(ERR_PT_LOGFAIL);
	} catch (...) {
		l_retpk.WriteShort(ERR_PT_LOGFAIL);
	}
	m_mtxSyn.unlock();

	return l_retpk;
}

WPacket GroupServerApp::OS_LOGIN(DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (pk.ReadShort() != std::stoi(m_cfg["Main"]["Version"])) {
		l_retpk.WriteShort(ERR_OS_NOTMATCH_VERSION);
		Disconnect(datasock, 100, -15);
		return l_retpk;
	}
	cChar* agentName = pk.ReadString();

	LG("Connect", "AgentServer:%s,%d OS_LOGIN1\\n", datasock->GetPeerIP(), datasock->GetPeerPort());

	m_mtxAgent.lock();

	LG("Connect", "AgentServer:%s,%d OS_LOGIN2\\n", datasock->GetPeerIP(), datasock->GetPeerPort());
	try {
		if (m_groupServerAgent.SetDataSock(datasock)) {
			l_retpk.WriteShort(ERR_SUCCESS);
			std::cout << "AgentServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "Re-log successful!" << std::endl;
		} else {
			l_retpk.WriteShort(ERR_PT_SAMEGATENAME);
			std::cout << "AgentServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "Login failed: A same name is already logged on in AgentServer" << std::endl;
			Disconnect(datasock);
		}
	} catch (...) {
	}
	m_mtxAgent.unlock();
	LG("Connect", "AgentServer:%s,%d OS_LOGIN3\\n", datasock->GetPeerIP(), datasock->GetPeerPort());

	return l_retpk;
}

void GroupServerApp::OS_PING(DataSocket* datasock, RPacket& pk) {
	WPacket l_wpk = GetWPacket();
	l_wpk.WriteCmd(CMD_SO_PING);
	l_wpk.WriteLong(m_plyheap.GetUsedNum());
	SendData(datasock, l_wpk);
}
// End

void GroupServerApp::CP_PING(Player* ply, DataSocket* datasock, RPacket& pk) {
	Player* l_ply = ply->m_pingply;
	if (!l_ply)
		return;
	ply->m_pingply = 0;
	// l_ply->SendSysInfo(dstring("�t???��?�??�??")<<ply->m_chaname[ply->m_currcha].c_str()<<"??�?ping?�?a:"<<pk.ReadLong()<<"o�??");
	char l_buf[256];
	sprintf(l_buf, RES_STRING(GP_GROUPSERVERAPPMASTER_CPP_00001), ply->m_chaname[ply->m_currcha].c_str(), pk.ReadLong());
	l_ply->SendSysInfo(l_buf);
}

void GroupServerApp::CP_REPORT_WG(Player* ply, DataSocket* datasock, RPacket& pk) {
	// �3??�??��1�?�a1��y�?
	if (!ply->m_bWG) {
		ply->m_bWG = TRUE;
		m_curWGChaNum++;
	}
	// ply->SendSysInfo( "��??�???�?�1�?�a1�??" );
}

void GroupServerApp::KickUser(DataSocket* datasock, uintptr_t gpaddr, uintptr_t gtaddr) {
	WPacket l_wpk = GetWPacket();
	l_wpk.WriteCmd(CMD_PT_KICKUSER);
	l_wpk.WriteLongLong(gpaddr);
	l_wpk.WriteLongLong(gtaddr);
	l_wpk.WriteShort(1);
	SendData(datasock, l_wpk);
}

WPacket GroupServerApp::TP_LOGIN(DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (pk.ReadShort() != std::stoi(m_cfg["Main"]["Version"])) {
		l_retpk.WriteShort(ERR_PT_LOGFAIL);
		Disconnect(datasock, 100, -15);
		return l_retpk;
	}
	cChar* l_gatename = pk.ReadString();
	LG("Connect", "GateServer:%s,%d TP_LOGIN1\\n", datasock->GetPeerIP(), datasock->GetPeerPort());

	m_mtxlogin.lock();
	LG("Connect", "GateServer:%s,%d TP_LOGIN2\\n", datasock->GetPeerIP(), datasock->GetPeerPort());

	try {
		GateServer* l_gate = FindGateSByName(l_gatename);
		if (l_gate) {
			if (l_gate->SetDataSock(datasock)) {
				// Add by lark.li 20081119 begin
				l_gate->SetSync();
				// End

				l_retpk.WriteShort(ERR_SUCCESS);
				std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "re login success!" << std::endl;
			} else {
				l_retpk.WriteShort(ERR_PT_SAMEGATENAME);
				std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "login failed: exsit the same name's GateServer " << std::endl;
				Disconnect(datasock);
			}
		} else if (m_gatenum < GATE_MAX) {
			// Add by lark.li 20081119 begin
			m_gate[m_gatenum].SetSync();
			// End

			l_retpk.WriteShort(ERR_SUCCESS);
			m_gate[m_gatenum].m_name = l_gatename;
			m_gate[m_gatenum].SetDataSock(datasock);
			m_gatenum++;
			std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "login success" << std::endl;
		} else {
			l_retpk.WriteShort(ERR_PT_LOGFAIL);
			std::cout << "GateServer:" << datasock->GetPeerIP() << "," << datasock->GetPeerPort() << "login failed!" << std::endl;
			Disconnect(datasock);
		}
	} catch (...) {
	}
	m_mtxlogin.unlock();
	LG("Connect", "GateServer:%s,%d TP_LOGIN3\\n", datasock->GetPeerIP(), datasock->GetPeerPort());

	return l_retpk;
}

WPacket GroupServerApp::TP_REQPLYLST(DataSocket* datasock, RPacket& pk) {
	GateServer* l_gate = (GateServer*)datasock->GetPointer();
	if (!l_gate) {
		return 0;
	}
	WPacket l_retpk = GetWPacket();
	Player* l_ply;
	uShort l_plynum = 0;
	RunChainGetArmor<Player> l(m_plylst);
	for (l_ply = m_plylst.GetNextItem(); l_ply; l_ply = m_plylst.GetNextItem()) {
		if (l_ply->m_gate != l_gate || l_ply->m_currcha < 0)
			continue;
		l_retpk.WriteLongLong(l_ply->m_gtAddr);
		l_retpk.WriteLong(l_ply->m_chaid[l_ply->m_currcha]);
		l_plynum++;
	}
	l.unlock();
	l_retpk.WriteShort(l_plynum);
	return l_retpk;
}

bool GroupServerApp::GetCHAsFromDBByPlayer(Player* player, WPacket& wpk) {
	auto db = GetDB();
	if (!db) {
		LG("DBPool", "GetCHAsFromDBByPlayer: failed to get DB connection for %s\n", player->m_acctname.c_str());
		return false;
	}
	int l_row = 0;
	if ((l_row = db->tblaccounts->FetchRowByActName(player->m_acctname.c_str())) == 0) // ?????
	{
		player->m_bNew = true;
		player->m_password.clear();
		if (!db->tblaccounts->InsertRow(player->m_acctLoginID, player->m_acctname.c_str(), "0"))
			return false;
		if (!db->tblaccounts->FetchRowByActName(player->m_acctname.c_str()))
			return false;
		player->m_acctid = db->tblaccounts->GetActID();
		wpk.WriteChar(0); // ????
	} else if (l_row == 1) {
		player->m_bNew = false;
		player->m_acctid = db->tblaccounts->GetActID();
		player->m_password = db->tblaccounts->GetPassword();
		player->m_gm = db->tblaccounts->GetGM();
		std::string l_chaid[Player::emMaxCharacters];
		player->m_chanum = char(Util_ResolveTextLine(db->tblaccounts->GetChaIDs(), l_chaid, Player::emMaxCharacters, ';'));
		wpk.WriteChar(player->m_chanum); // ????

		char i = 0, j = 0;
		for (; j < player->m_chanum; i++, j++) {
			player->m_chaid[i] = atoi(l_chaid[j].c_str());
			if (!player->m_chaid[i]) {
				wpk.WriteChar(0);
				i--;
			} else {
				if ((l_row = db->tblcharaters->FetchRowByChaID(player->m_chaid[i])) == 1) {
					char* l_look = const_cast<char*>(db->tblcharaters->GetLook()); // ??????
					LOOK look;
					MemSet((char*)&look, 0, sizeof(LOOK));
					try {
						std::string s(l_look);
						Strin2LookData(&look, s);
					} catch (...) {
						wpk.WriteChar(0);
						i--;
						continue;
					}
					wpk.WriteChar(1); // ????????????
					player->m_chaname[i] = db->tblcharaters->GetChaName();
					player->m_motto[i] = db->tblcharaters->GetMotto();
					player->m_icon[i] = db->tblcharaters->GetIcon();
					player->m_guild[i] = db->tblcharaters->GetGuildID();
					player->m_guildPermission[i] = db->tblcharaters->GetGuildPermission();
					player->m_chatColour[i] = db->tblcharaters->GetChatColour(); // todo
					wpk.WriteString(db->tblcharaters->GetChaName());			   // ???
					wpk.WriteString(db->tblcharaters->GetJob());				   // ??
					wpk.WriteShort(db->tblcharaters->GetDegree());			   // ??
					wpk.WriteSequence((char*)&look, sizeof(LOOK));
				} else {
					wpk.WriteChar(0); // ????????????
					i--;
				}
			}
		}
		player->m_chanum = i;
	} else {
		LG("GroupServer", "enum account[%s] operate table account failed\n", player->m_acctname.c_str());
	}
	return true;
}

WPacket GroupServerApp::TP_USER_LOGIN(DataSocket* datasock, RPacket& pk) {
	// Reduced timeout from 25s to 8s to prevent thread exhaustion under attack
	uLong l_ulMilliseconds = 8 * 1000;
	uLong l_tick = GetTickCount() - pk.GetTickCount();

	if (l_ulMilliseconds > l_tick) {
		l_ulMilliseconds = l_ulMilliseconds - l_tick;

		WPacket l_retpk = 0;
		Player* l_ply = g_gpsvr->m_plyheap.Get();
		
		// Register player in validation registry immediately after allocation
		g_gpsvr->RegisterPlayer(l_ply);

		l_ply->m_gate = (GateServer*)datasock->GetPointer();
		l_ply->m_gtAddr = pk.ReverseReadLongLong();
		in_addr l_ina;
		l_ina.s_addr = pk.ReverseReadLong();
		strcpy(l_ply->m_clientip, inet_ntoa(l_ina));

		// Read this stuff but ignore it, as the packet was duplicated.
		//@to-do: add ReverseReadSequence/ReverseReadString.
		uShort cipherlen;
		uShort ivlen;
		pk.ReadSequence(cipherlen);
		pk.ReadSequence(ivlen);

		uShort l_len;
		cChar* l_passport = pk.ReadString(&l_len);
		if (!l_passport || strlen(l_passport) >= 64) {
			l_ply->Free();
			l_retpk = GetWPacket();
			l_retpk.WriteCmd(ERR_PT_INERR);
			return l_retpk;
		}
		l_ply->m_passport = l_passport;

		cChar* l_acctname = pk.ReadString(&l_len); // AcctName
		if (!l_acctname || strlen(l_acctname) > 128) {
			l_ply->Free();
			l_retpk = GetWPacket();
			l_retpk.WriteShort(ERR_PT_INERR);
			return l_retpk;
		}
		
		// SANITIZE: Validate account name for dangerous characters
		if (!PS::ValidateUsername(l_acctname)) {
			LG("Security", "[Login] Invalid username characters from IP %s: %s\n", l_ply->m_clientip, l_acctname);
			l_ply->Free();
			l_retpk = GetWPacket();
			l_retpk.WriteShort(ERR_PT_INVALIDDAT);
			return l_retpk;
		}
		if (m_plylst.GetTotal() >= const_cha.MaxLoginUsr) {
			l_ply->Free();
			l_retpk = GetWPacket();
			l_retpk.WriteShort(ERR_MC_TOOMANYPLY);
			return l_retpk;
		}
		l_ply->m_acctname = l_acctname;

		WPacket l_wpk = pk;
		l_wpk.WriteCmd(CMD_PA_USER_LOGIN);
		RPacket l_rpk = SyncCall(m_acctsock, l_wpk, l_ulMilliseconds); // ?AccountServer??
		uShort l_errno;
		
		if (!l_rpk.HasData()) {
			auto l_retpk = GetWPacket();
			l_retpk.WriteShort(ERR_PT_NETEXCP); // ???
			LG("GroupServer", "ip: %s username: %s login net failed\n", l_ply->m_clientip, l_ply->m_acctname.c_str());
			l_ply->Free();
			return l_retpk;
		} else if ((l_errno = l_rpk.ReadShort()) && (l_rpk.ReadCmd() == CMD_AP_KICKUSER)) {
			// Duplicate login - kick old session and retry
			RPacket l_kickpk = l_rpk;
			AP_KICKUSER(datasock, l_kickpk);
			l_rpk.DiscardLast(sizeof(uLong));
			l_retpk = l_rpk;
		} else if (l_errno) {
			// Other login error - return to client
			l_retpk = GetWPacket();
			l_retpk.WriteShort(l_errno);
			l_retpk = l_rpk;

			LG("GroupServer", "ip: %s username: %s login failed, error:%d\n", l_ply->m_clientip, l_ply->m_acctname.c_str(), l_errno);
			l_ply->Free();
		} else {
			l_ply->m_acctLoginID = l_rpk.ReadLong();
			l_ply->m_sessid = l_rpk.ReadLong();

			l_retpk = GetWPacket();
			l_retpk.WriteShort(ERR_SUCCESS); // ?????

			GetCHAsFromDBByPlayer(l_ply, l_retpk); // ??????????

			// Check maintenance mode - only allow HD accounts (GM level 30+)
			if (IsMaintenanceMode() && l_ply->m_gm < 30) {
				LG("GroupServer", "ip: %s username: %s login blocked: maintenance mode active (GM level %d < 30)\n", 
					l_ply->m_clientip, l_ply->m_acctname.c_str(), l_ply->m_gm);
				
				// Notify AccountServer to release this login session
				WPacket l_logoutpk = GetWPacket();
				l_logoutpk.WriteCmd(CMD_PA_USER_BILLEND);
				l_logoutpk.WriteString(l_ply->m_acctname.c_str());
				SendData(m_acctsock, l_logoutpk);
				
				l_retpk = GetWPacket();
				l_retpk.WriteShort(ERR_MC_MAINTENANCE);
				l_ply->Free();
				return l_retpk;
			}

			if (l_ply->m_password.length() < 32) {
				LG("ErrorServer", "account:%s ID:%d PW2:%s\n", l_ply->m_acctname.c_str(), l_ply->m_acctid, l_ply->m_password.c_str());
			}

			if (l_ply->m_password.length() > 0 && !l_ply->m_bNew) {
				l_retpk.WriteChar(1);
			} else {
				l_retpk.WriteChar(0);
			}

			l_retpk.WriteLong(l_ply->m_acctid);
			l_retpk.WriteLong(l_ply->m_acctLoginID);
			l_retpk.WriteLongLong(MakeULong(l_ply)); // ????????

			// Atomic insert to catch race conditions (two logins for same account within milliseconds)
			// First remove any stale entry from previous session (in case of reconnect after kick)
			m_LoginList.Remove(l_acctname);
			if (!m_LoginList.Insert(l_acctname)) {
				// Race condition: another login for this account just completed
				LG("GroupServer", "Account %s blocked: race condition detected (already in LoginList)\n", l_acctname);
				l_retpk = GetWPacket();
				l_retpk.WriteCmd(CMD_MC_LOGIN);
				l_retpk.WriteShort(ERR_AP_LOGGED);  // "This account is already online"
				l_ply->Free();
				return l_retpk;
			}

			l_ply->BeginRun();
			// AddPlayerToList(l_ply->m_chaid[l_ply->m_currcha], l_ply);
			LG("GroupServer", "(%s):[%s]login success, \t nline/total:%d/%d\n", l_ply->m_clientip, l_ply->m_acctname.c_str(), m_plylst.GetTotal(), int(m_curChaNum));
		}
		return l_retpk;
	} else {
		WPacket l_retpk = GetWPacket();
		l_retpk.WriteShort(ERR_PT_NETEXCP); // ???
		LG("GroupServer", "authentication packet time out.\n");
		return l_retpk;
	}
}

void GroupServerApp::AP_KICKUSER2(DataSocket* datasock, uLong acctid) {
	Player* l_ply = 0;
	uLong l_acctid = acctid;
	RunChainGetArmor<Player> l(m_plylst);
	for (l_ply = m_plylst.GetNextItem(); l_ply; l_ply = m_plylst.GetNextItem()) {
		if (l_ply->m_acctid == l_acctid) {
			break;
		}
	}
	if (l_ply) {
		l_ply->EndPlay(datasock);
		if (l_ply->EndRun()) {
			if (l_ply->m_currcha != -1) {
				//?�AccountServer�??�?��???�??��?
				WPacket l_wpk = GetWPacket();
				l_wpk.WriteCmd(CMD_PA_USER_BILLEND);
				l_wpk.WriteString(l_ply->m_acctname.c_str());
				SendData(m_acctsock, l_wpk);
			}
			////?�AccountServer�??�LogOut?��?
			WPacket l_wpk = GetWPacket();
			// l_wpk.WriteCmd(CMD_PA_USER_LOGOUT);
			// l_wpk.WriteLong(l_ply->m_acctid);
			// l_wpk.WriteLong(l_ply->m_sessid);
			// SendData(m_acctsock,l_wpk);
			//?�GateServer�??��?�??��?
			// l_wpk	=GetWPacket();
			l_wpk.WriteCmd(CMD_AP_KICKUSER);
			SendToClient(l_ply, l_wpk);
			// �?�?3�1|
			LG("GroupServer", "recieved killed acctid/acctname:[%d]/[%s] command!\n", l_acctid, l_ply->m_acctname.c_str());
		}
		m_LoginList.Remove(l_ply->m_acctname);
		l_ply->Free();
	} else {
		l.unlock();
		LG("GroupServer", "recieved kill acctid:[%d] command(not in play list)!\n", l_acctid);
	}
}

void GroupServerApp::KillUserByName(const char* accoutName) {
	Player* l_ply = 0;
	RunChainGetArmor<Player> l(m_plylst);
	for (l_ply = m_plylst.GetNextItem(); l_ply; l_ply = m_plylst.GetNextItem()) {
		if (strcmp(l_ply->m_acctname.c_str(), accoutName) == 0) {
			break;
		}
	}
	if (l_ply) {
		l_ply->EndPlay(nullptr);
		{
			// Notify AccountServer about logout
			WPacket l_wpk = GetWPacket();
			l_wpk.WriteCmd(CMD_PA_USER_LOGOUT);
			l_wpk.WriteLong(l_ply->m_acctid);
			l_wpk.WriteLong(l_ply->m_sessid);
			SendData(m_acctsock, l_wpk);
			
			// Send kick to GateServer
			/*WPacket*/ l_wpk = GetWPacket();
			l_wpk.WriteCmd(CMD_AP_KICKUSER);
			SendToClient(l_ply, l_wpk);
			
			LG("GroupServer", "KillUserByName: killed account [%s]\n", l_ply->m_acctname.c_str());
		}
		// Remove from login list
		m_LoginList.Remove(l_ply->m_acctname);
		// Remove from player list and free
		l_ply->EndRun();
		l_ply->Free();
	} else {
		l.unlock();
	}
}

void GroupServerApp::AP_KICKUSER(DataSocket* datasock, RPacket& pk) {
	Player* l_ply = 0;
	uLong l_acctid = pk.ReadLong();
	RunChainGetArmor<Player> l(m_plylst);
	for (l_ply = m_plylst.GetNextItem(); l_ply; l_ply = m_plylst.GetNextItem()) {
		if (l_ply->m_acctLoginID == l_acctid) {
			break;
		}
	}
	if (l_ply) {
		l_ply->EndPlay(datasock);
		if (l_ply->EndRun()) {
			if (l_ply->m_currcha != -1) {
				// Notify AccountServer about billing end
				WPacket l_wpk = GetWPacket();
				l_wpk.WriteCmd(CMD_PA_USER_BILLEND);
				l_wpk.WriteString(l_ply->m_acctname.c_str());
				SendData(m_acctsock, l_wpk);
			}
			// Notify AccountServer to logout (set status to OFFLINE)
			// This is critical for duplicate login handling - allows new login to proceed
			{
				WPacket l_wpk = GetWPacket();
				l_wpk.WriteCmd(CMD_PA_USER_LOGOUT);
				l_wpk.WriteLong(l_ply->m_acctid);
				l_wpk.WriteLong(l_ply->m_sessid);
				SendData(m_acctsock, l_wpk);
			}
			// Notify GateServer to disconnect the client
			WPacket l_wpk = GetWPacket();
			l_wpk.WriteCmd(CMD_AP_KICKUSER);
			SendToClient(l_ply, l_wpk);
			LG("GroupServer", "kicked acctid/acctname:[%d]/[%s] due to duplicate login\n", l_ply->m_acctid, l_ply->m_acctname.c_str());
		}
		m_LoginList.Remove(l_ply->m_acctname);
		l_ply->Free();
	} else {
		l.unlock();
		// Player not found - likely stale session after server restart
		// Still notify AccountServer to clear the account status so new login can proceed
		LG("GroupServer", "recieved kick acctid:[%d] command (not in play list) - clearing stale session\n", l_acctid);
		WPacket l_wpk = GetWPacket();
		l_wpk.WriteCmd(CMD_PA_USER_LOGOUT);
		l_wpk.WriteLong(l_acctid);  // Use the acctLoginID from kick command
		l_wpk.WriteLong(0);         // Session ID unknown, but logout should still work
		SendData(m_acctsock, l_wpk);
	}
}

void GroupServerApp::AP_EXPSCALE(DataSocket* datasock, RPacket& pk) {
	//  ��3�??
	Player* l_ply = 0;
	uLong ulChaID = pk.ReadLong();
	uLong ulTime = pk.ReadLong();

	RunChainGetArmor<Player> l(m_plylst);
	for (l_ply = m_plylst.GetNextItem(); l_ply; l_ply = m_plylst.GetNextItem()) {
		if (l_ply->m_acctLoginID == ulChaID) {
			break;
		}
	}

	if (l_ply) {
		WPacket l_wpk = GetWPacket();
		l_wpk.WriteCmd(CMD_PM_EXPSCALE);
		l_wpk.WriteLong(l_ply->m_chaid[l_ply->m_currcha]);
		l_wpk.WriteLong(ulTime);

		// l_ply->m_gate->GetDataSock()->SendData(l_wpk);
		SendToClient(l_ply, l_wpk);
	}
}

void GroupServerApp::TP_DISC(DataSocket* datasock, RPacket& pk) {
	uLong l_actid = pk.ReadLong();
	in_addr l_ina;
	l_ina.s_addr = pk.ReadLong();
	cChar* l_reason = pk.ReadString();
	auto db = GetDB();
	if (db) db->tblaccounts->SetDiscInfo(l_actid, inet_ntoa(l_ina), l_reason);
}

void GroupServerApp::TP_ESTOPUSER_CHECK(DataSocket* datasock, RPacket& pk) {
	Player* l_ply = 0;
	uLong l_acctid = pk.ReadLong();
	RunChainGetArmor<Player> l(m_plylst);
	for (l_ply = m_plylst.GetNextItem(); l_ply; l_ply = m_plylst.GetNextItem()) {
		if (l_ply->m_acctid == l_acctid) {
			break;
		}
	}
	if (l_ply) {
		l_ply->IsEstop();
	}
}

WPacket GroupServerApp::TP_USER_LOGOUT(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	uLong l_acctid = ply->m_acctid;
	RunChainGetArmor<Player> l(m_plylst);
	if (!ply || !ply->m_gtAddr || !l_acctid || l_acctid != ply->m_acctid) {
		l_retpk.WriteShort(ERR_PT_INERR);
		return l_retpk;
	}

	// Clean up any pending guild bank requests for this player
	RemovePlayerFromGuildBankQueue(ply);

	if (ply->m_bCheat) {
		if (m_dwCheatCount > 0)
			m_dwCheatCount--;
	}

	ply->EndPlay(datasock);

	if (ply->EndRun()) {
		if (ply->m_currcha != -1) {
			// ????????
		}

		// ?AccountServer??LogOut??
		WPacket l_wpk = GetWPacket();
		l_wpk.WriteCmd(CMD_PA_USER_LOGOUT);
		l_wpk.WriteLong(ply->m_acctLoginID);
		l_wpk.WriteLong(ply->m_sessid);
		SendData(m_acctsock, l_wpk);
		// ????
		LG("GroupServer", "(%s):[%s]logout,\t online/total:%d/%d\n", ply->m_clientip, ply->m_acctname.c_str(), m_plylst.GetTotal(), int(m_curChaNum));
	} else {
		LG("GroupServer", "(%s):[%s]%s%d/%d\n", ply->m_clientip, ply->m_acctname.c_str(), RES_STRING(GP_GROUPSERVERAPPSERV_CPP_00026), m_plylst.GetTotal(), int(m_curChaNum));
	}

	if (ply->m_bWG) {
		m_curWGChaNum--;
	}

	m_LoginList.Remove(ply->m_acctname);
	ply->Free();
	l.unlock();
	// ???????
	l_retpk.WriteShort(ERR_SUCCESS);
	return l_retpk;
}

WPacket GroupServerApp::TP_BGNPLAY(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (ply->m_currcha >= 0) {
		l_retpk.WriteShort(ERR_PT_INERR); // ?????????
	} else {
		uShort l_len;
		cChar* l_cha = pk.ReadString(&l_len);
		if (!l_cha || l_len > common::conformity::character::name::max_length) {
			l_retpk.WriteShort(ERR_PT_INERR); // ?????????
		} else {
			MutexArmor l_lockCha(ply->m_mtxCha);
			ply->m_bp_currcha = ply->FindIndexByChaName(l_cha);
			if (ply->m_bp_currcha < 0) // ?????????
			{
				l_retpk.WriteShort(ERR_PT_INVALIDCHA);
			} else {
				// Check if this character is already being played (e.g. from a previous session that didn't logout properly)
				// If so, kick the existing player first
				short cha_index = ply->m_bp_currcha;
				Player* playing_player = GetPlayerByChaID(ply->m_chaid[cha_index]);
				if (playing_player && playing_player != ply) {
					LG("GroupServer", "Character %s already playing, kicking old session.\n", l_cha);
					// Logout the old player
					RPacket rpk{ nullptr };
					TP_USER_LOGOUT(playing_player, datasock, rpk);
				}
				
				if (ply->m_password.length() <= 0) {
					l_retpk.WriteShort(ERR_PT_INVALID_PW2);
				} else // ????
				{
				auto db = GetDB();
				if (!db) {
					l_retpk.WriteShort(ERR_PT_SERVERBUSY);
				} else if (db->tblcharaters->FetchRowByChaID(ply->m_chaid[ply->m_bp_currcha]) < 1) {
					l_retpk.WriteShort(ERR_PT_INERR);
				} else {
					ply->m_guildPermission[ply->m_bp_currcha] = db->tblcharaters->GetGuildPermission();
					ply->m_chatColour[ply->m_bp_currcha] = db->tblcharaters->GetChatColour(); // fixed  chat color for first login // mothannakh
					int l_maxval = std::stoi(m_cfg["Database"]["MaxVal"]);
					if (l_maxval && (db->tblcharaters->GetStr() > l_maxval || db->tblcharaters->GetDex() > l_maxval || db->tblcharaters->GetAgi() > l_maxval || db->tblcharaters->GetCon() > l_maxval || db->tblcharaters->GetSta() > l_maxval || db->tblcharaters->GetLuk() > l_maxval)) {
						l_retpk.WriteShort(ERR_PT_BADBOY);
						WPacket l_wpk = GetWPacket();
						l_wpk.WriteCmd(CMD_MC_SYSINFO);
						// l_wpk.WriteString(dstring("????????????BT??[??:")<<ply->m_acctname.c_str()<<",??:"<< ply->m_chaname[ply->m_bp_currcha].c_str()<<"]?");
						char l_buf[256];
						sprintf(l_buf, RES_STRING(GP_GROUPSERVERAPPSERV_CPP_00002), ply->m_acctname.c_str(), ply->m_chaname[ply->m_bp_currcha].c_str());
						l_wpk.WriteString(l_buf);

						Player* l_plylst[10240];
						short l_plynum = 0;

						RunChainGetArmor<Player> l(m_plylst);
						for (Player* l_plyr = m_plylst.GetNextItem(); l_plyr; l_plyr = m_plylst.GetNextItem()) {
							if (l_plyr->m_bp_currcha < 0)
								continue;
							l_plylst[l_plynum] = l_plyr;
							l_plynum++;
						}
						l.unlock();
						SendToClient(l_plylst, l_plynum, l_wpk);
						ply->m_currcha = -1;
					} else {
						short swiner = 0;
						// ????????
						l_retpk.WriteShort(ERR_SUCCESS); // ???????
						l_retpk.WriteString(ply->m_password.c_str());
						l_retpk.WriteLong(ply->m_chaid[ply->m_bp_currcha]); // ??ID
						l_retpk.WriteLong(ply->m_chaid[ply->m_bp_currcha]); // WorldID
						l_retpk.WriteString(db->tblcharaters->GetMap());		// ????????
						for (int i = 0; i < MAXORDERNUM; i++) {
							if (ply->m_chaid[ply->m_bp_currcha] == db->tblparam->GetOrderData(i)->nid) {
								swiner = i + 1;
								break;
							}
						}
						l_retpk.WriteShort(swiner);
						LG("GroupServer", "(%s):[%s]select char[%s]begin paly...,\t online/total:%d/%d\n",
						   ply->m_clientip, ply->m_acctname.c_str(), l_cha, m_plylst.GetTotal(), int(m_curChaNum));
					}
				}
				}
			}
			l_lockCha.unlock();
		}
	}
	return l_retpk;
}

WPacket GroupServerApp::TP_ENDPLAY(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (ply->m_currcha < 0) {
		l_retpk.WriteShort(ERR_PT_INERR);
	} else {
		ply->EndPlay(datasock);

		LG("GroupServer", "(%s):[%s]exit char[%s]begin entry select char UI...,\t online/total:%d/%d\n",
		   ply->m_clientip, ply->m_acctname.c_str(), ply->m_chaname[ply->m_currcha].c_str(), m_plylst.GetTotal(), int(m_curChaNum));

		ply->m_currcha = -1;
		ply->EndPlayReset();

		// Write SUCCESS first, then append character list data directly
		l_retpk.WriteShort(ERR_SUCCESS);
		if (!GetCHAsFromDBByPlayer(ply, l_retpk)) {
			// DB failed — GetCHAsFromDBByPlayer may not have written the char count byte.
			// Write 0 characters so the client gets a valid (empty) character list
			// rather than parsing garbage data from the packet.
			l_retpk.WriteChar(0);
			LG("GroupServer", "TP_ENDPLAY: GetCHAsFromDBByPlayer failed for %s, sending empty character list\n", ply->m_acctname.c_str());
		}
	}
	return l_retpk;
}

void GroupServerApp::MP_ENTERMAP(Player* ply, DataSocket* datasock, RPacket& pk) {
	// Safety check: validate player pointer before accessing members
	if (!ply) {
		LG("Security", "MP_ENTERMAP: Received null player pointer from %s\n", datasock->GetPeerIP());
		return;
	}

	char l_isSwitch;
	if (!(l_isSwitch = pk.ReadChar()) && ply->m_currcha < 0) {
		MP_ONLINE(ply);
	} else if (l_isSwitch && ply->m_currcha >= 0) {
		MP_SWITCH(ply);
	}
}

void GroupServerApp::MP_ONLINE(Player* ply) {
	// Validate player and character index before proceeding
	if (!ply) {
		LG("Security", "MP_ONLINE: Received null player pointer\n");
		return;
	}

	// Validate m_bp_currcha is within valid bounds (0 to emMaxCharacters-1)
	if (ply->m_bp_currcha < 0 || ply->m_bp_currcha >= Player::emMaxCharacters) {
		LG("Security", "MP_ONLINE: Invalid m_bp_currcha=%d for player %s\n", 
		   ply->m_bp_currcha, ply->m_acctname.c_str());
		return;
	}

	MutexArmor l_lockDB(m_mtxDB);
	AddPlayerToList(ply->m_chaid[ply->m_bp_currcha], ply);
	ply->m_currcha = ply->m_bp_currcha;
	ply->m_bp_currcha = -1;
	auto db = GetDB();
	if (db) {
		db->tblcharaters->SetAddr(ply->m_chaid[ply->m_currcha], MakeULong(ply));
	}
	++m_curChaNum;
	LG("GroupServer", "(%s):[%s] char [%s]entry map server begin play...!\t online/total:%d/%d\n",
	   ply->m_clientip, ply->m_acctname.c_str(), ply->m_chaname[ply->m_currcha].c_str(),
	   m_plylst.GetTotal(), int(m_curChaNum));

	ply->CheckEstop();

	PC_FRND_INIT(ply);
	PC_GULD_INIT(ply);
	PC_MASTER_INIT(ply);
}

WPacket GroupServerApp::TP_NEWCHA(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (ply->m_currcha >= 0) {
		l_retpk.WriteShort(ERR_PT_INERR); // ????????????
		return l_retpk;
	}
	MutexArmor l_lockCha(ply->m_mtxCha);
	if (ply->m_chanum >= const_cha.MaxChaNum) // ????????????
	{
		l_retpk.WriteShort(ERR_PT_TOMAXCHA);
		return l_retpk;
	}
	uShort l_len;
	cChar* l_chaname = pk.ReadString(&l_len);
	if (!l_chaname) {
		l_retpk.WriteShort(ERR_PT_INERR);
		return l_retpk;
	}
	if (l_len > common::conformity::character::name::max_length) {
		l_retpk.WriteShort(ERR_PT_TOOBIGCHANM);
		return l_retpk;
	}
	
	// SANITIZE: Check for dangerous characters (SQL injection, XSS)
	if (!PS::IsSafeString(l_chaname)) {
		LG("Security", "[NewCha] Dangerous characters in character name from account %s\n", ply->m_acctname.c_str());
		l_retpk.WriteShort(ERR_PT_ERRCHANAME);
		return l_retpk;
	}

	if (!common::conformity::character::name::is_valid(l_chaname, l_len) ||
		!CTextFilter::IsLegalText(CTextFilter::NAME_TABLE, l_chaname)) {
		l_retpk.WriteShort(ERR_PT_ERRCHANAME);
		return l_retpk;
	}
	// cChar	*	l_birth			=pk.ReadString(&l_len);
	// dstring		l_birth1	="";
	// cChar	*	l_birth2		=0;
	// if(l_birth && l_len <30 && !strchr(l_birth,'/'))
	//{
	//	l_birth1	=dstring("/")<<l_birth<<"/";

	//	try{
	//		l_birth2		=this->m_cfg["??"]["???"];
	//	}catch(...)
	//	{
	//		l_birth2		=0;
	//	}
	//}else
	//{
	//	l_birth2	=0;
	//}
	// if(!l_birth2 ||!strstr(l_birth2,l_birth1))
	//{
	//	l_retpk.WriteShort(ERR_PT_INVALIDBIRTH);		//?????
	//}else
	//{
	cChar* l_birth = pk.ReadString(&l_len);
	dstring l_birth1 = "";
	cChar* l_map = 0;
	if (l_birth && l_len < 30 && !strchr(l_birth, '/')) {
		l_birth1 = l_birth;
		try {
			map<string, string>::iterator it = m_mapBirthplace.find(string(l_birth));

			if (it != m_mapBirthplace.end()) {
				l_map = it->second.c_str();
			}
		} catch (...) {
			l_map = 0;
		}
	} else {
		l_map = 0;
	}
	if (!l_map) {
		l_retpk.WriteShort(ERR_PT_INVALIDBIRTH); // ?????
		return l_retpk;
	}
	// const LOOK	*look	=reinterpret_cast<const LOOK*>(pk.ReadSequence(l_len));
	//
	// if(!look || l_len !=sizeof(LOOK))
	//{
	//	l_retpk.WriteShort(ERR_PT_INVALIDDAT);
	//	return l_retpk;
	// }
	char l_look[defLOOK_DATA_STRING_LEN];

	int typeID = pk.ReadLong();
	int hairID = pk.ReadLong();
	int faceID = pk.ReadLong();

	// cout << typeID << "\n" << hairID << "\n" << faceID << "\n";

	// validate type (1/2/3/4)
	if (typeID > 4 || typeID < 1) {
		LG("security", "[NewCha] Invalid typeID %d from account %s\n", typeID, ply->m_acctname.c_str());
		l_retpk.WriteShort(ERR_PT_INVALIDDAT);
		return l_retpk;
	}

	int nHairTestCnt[4] = {2000, 2062, 2124, 2291};
	int nFaceTestCnt[4] = {2554, 2554, 2554, 2554};
	int nSelHairNum[4] = {8, 8, 8, 4};
	int nSelFaceNum[4] = {8, 8, 8, 8};

	int index = typeID - 1;
	if (hairID < nHairTestCnt[index] || hairID >= nHairTestCnt[index] + nSelHairNum[index]) {
		LG("security", "[NewCha] Invalid hairID %d (valid: %d-%d) from account %s\n", 
			hairID, nHairTestCnt[index], nHairTestCnt[index] + nSelHairNum[index] - 1, ply->m_acctname.c_str());
		l_retpk.WriteShort(ERR_PT_INVALIDDAT);
		return l_retpk;
	}
	if (faceID < nFaceTestCnt[index] || faceID >= nFaceTestCnt[index] + nSelFaceNum[index]) {
		LG("security", "[NewCha] Invalid faceID %d (valid: %d-%d) from account %s\n", 
			faceID, nFaceTestCnt[index], nFaceTestCnt[index] + nSelFaceNum[index] - 1, ply->m_acctname.c_str());
		l_retpk.WriteShort(ERR_PT_INVALIDDAT);
		return l_retpk;
	}

	stNetChangeChaPart part;
	// Fix: Zero-initialize the entire structure to prevent garbage values in checksum calculation
	memset(&part, 0, sizeof(part));

	part.sHairID = hairID;
	part.SLink[enumEQUIP_FACE].sID = faceID;
	part.sTypeID = typeID;

	const LOOK* look = reinterpret_cast<const LOOK*>(reinterpret_cast<char*>(&part));

	// if(!look || l_len !=sizeof(LOOK))
	//{
	//	l_retpk.WriteShort(ERR_PT_INVALIDDAT);
	//	return l_retpk;
	// }

	try {
		if (!LookData2String(look, l_look, defLOOK_DATA_STRING_LEN)) {
			l_retpk.WriteShort(ERR_PT_INVALIDDAT);
			return l_retpk;
		}
	} catch (...) {
		LG("GroupServer", "account[%s]new char[%s]find appreance data convert exception\n", ply->m_acctname.c_str(), l_chaname);
		l_retpk.WriteShort(ERR_PT_INVALIDDAT);
		return l_retpk;
	}
	auto db = GetDB();
	if (!db) {
		l_retpk.WriteShort(ERR_PT_SERVERBUSY);
		return l_retpk;
	}
	if (!db->tblcharaters->InsertRow(l_chaname, ply->m_acctid, l_birth, l_map, l_look)) // ?????
	{
		LG("GroupServer", "account[%s]new char[%s]the same name exception\n", ply->m_acctname.c_str(), l_chaname);
		l_retpk.WriteShort(ERR_PT_SAMECHANAME);
		return l_retpk;
	}
	l_retpk.WriteShort(ERR_SUCCESS);
	// ???????????ID??CharIDs
	if (db->tblcharaters->FetchRowByChaName(l_chaname) < 1) {
		l_retpk.WriteShort(ERR_PT_INERR);
		LG("GroupServer", "account[%s] when create char , can't restore database failed.\n", ply->m_acctname.c_str());
		return l_retpk;
	}
	ply->m_chaid[ply->m_chanum] = db->tblcharaters->Getcha_id();
	ply->m_chaname[ply->m_chanum] = l_chaname;
	ply->m_motto[ply->m_chanum] = db->tblcharaters->GetMottonByName();
	ply->m_icon[ply->m_chanum] = db->tblcharaters->GetIconByName();
	ply->m_guild[ply->m_chanum] = 0;
	ply->m_chanum++;

	char l_CharIDs[80];
	l_CharIDs[0] = 0;
	char l_buf[20];
	for (char i = 0; i < ply->m_chanum; i++) {
		strcat(l_CharIDs, itoa(ply->m_chaid[i], l_buf, 10));
		strcat(l_CharIDs, ";");
	}
	db->tblaccounts->UpdateRow(ply->m_acctid, l_CharIDs);
	LG("GroupServer", "(%s):[%s]create char [%s],\t online/total:%d/%d\n",
	   ply->m_clientip, ply->m_acctname.c_str(), l_chaname, m_plylst.GetTotal(), int(m_curChaNum));
	return l_retpk;
}

WPacket GroupServerApp::TP_DELCHA(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	if (ply->m_currcha >= 0) {
		l_retpk.WriteShort(ERR_PT_INERR); // ????????????h?�???
	} else {
		uShort l_len, l_len2;
		cChar* l_cha = pk.ReadString(&l_len);
		cChar* l_pw2 = pk.ReadString(&l_len2);
		if (!l_cha || l_len > common::conformity::character::name::max_length) {
			l_retpk.WriteShort(ERR_PT_INERR);
		} else if (strcmp(l_pw2, ply->m_password.c_str()) != 0) {
			l_retpk.WriteShort(ERR_PT_INVALID_PW2);
		} else {
			MutexArmor l_lockCha(ply->m_mtxCha);
			char l_chaidx = ply->FindIndexByChaName(l_cha);
			if (l_chaidx < 0) // ???"?�????????
			{
				l_retpk.WriteShort(ERR_PT_INVALIDCHA);
			} else if (FindGuildByLeadID(ply->m_chaid[l_chaidx])) // ????L??
			{
				l_retpk.WriteShort(ERR_PT_ISGLDLEADER);
			} else {
				bool bFlag = false;
				int l_chaid = ply->m_chaid[l_chaidx];
				char l_CharIDs[80];
				l_CharIDs[0] = 0;
				char l_buf[20];
				for (char i = 0; i < ply->m_chanum; i++) {
					if (i == l_chaidx)
						continue;
					// strcat(l_CharIDs,itoa(ply->m_chaid[i],l_buf,10));
					_itoa_s(ply->m_chaid[i], l_buf, sizeof(l_buf), 10);
					strncat_s(l_CharIDs, sizeof(l_CharIDs), l_buf, _TRUNCATE);
					// strcat(l_CharIDs,";");
					strncat_s(l_CharIDs, sizeof(l_CharIDs), ";", _TRUNCATE);
				}

				auto db = GetDB();
				if (!db) {
					bFlag = false;
				} else {
					// Transaction uses the same connection's db for begin/commit/rollback
					if (db->db->begin_tran()) {
						if (!db->tblaccounts->UpdateRow(ply->m_acctid, l_CharIDs) || !db->tblcharaters->BackupRow(l_chaid) || !db->db->commit_tran()) {
							db->db->rollback();
						} else {
							bFlag = true;
						}
					}
				}

				if (bFlag) {
					l_retpk.WriteShort(ERR_SUCCESS); // ?????????????
					ply->m_chanum--;
					for (; l_chaidx < ply->m_chanum; l_chaidx++) {
						ply->m_chaid[l_chaidx] = ply->m_chaid[l_chaidx + 1];
						ply->m_chaname[l_chaidx] = ply->m_chaname[l_chaidx + 1];
						ply->m_motto[l_chaidx] = ply->m_motto[l_chaidx + 1];
						ply->m_icon[l_chaidx] = ply->m_icon[l_chaidx + 1];
						ply->m_guild[l_chaidx] = ply->m_guild[l_chaidx + 1];
					}

					LG("GroupServer", "(%s):[%s]%s%s%s%d/%d\n",
					   ply->m_clientip, ply->m_acctname.c_str(), RES_STRING(GP_GROUPSERVERAPPSERV_CPP_00043),
					   l_cha, RES_STRING(GP_GROUPSERVERAPPSERV_CPP_00044), m_plylst.GetTotal(), int(m_curChaNum));
				} else {
					l_retpk.WriteShort(ERR_PT_SERVERBUSY); // ??????�???????
					LG("GroupServer", "(%s):[%s]delete char failed[%s]?\t GetTotal/m_curChaNum:%d/%d\n",
					   ply->m_clientip, ply->m_acctname.c_str(), l_cha, m_plylst.GetTotal(), int(m_curChaNum));
				}
			}
			l_lockCha.unlock();
		}
	}
	return l_retpk;
}

WPacket GroupServerApp::TP_CREATE_PASSWORD2(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();
	dbc::uShort seq_len;
	const auto seq = pk.ReadString(&seq_len);
	std::string strPassword(seq, seq_len);

	if (ply->m_password.length() == 0 && strPassword.length() <= ROLE_MAXSIZE_PASSWORD2) {
		auto db = GetDB();
		if (!db) {
			l_retpk.WriteShort(ERR_PT_SERVERBUSY);
			return l_retpk;
		}
		if (db->tblaccounts->UpdatePassword(ply->m_acctid, strPassword.c_str())) {
			ply->m_password = strPassword;
			l_retpk.WriteShort(ERR_SUCCESS);
			LG("ErrorServer", "account:%s ID:%d database operate success:(%s)\n", ply->m_acctname.c_str(), ply->m_acctid, strPassword.c_str());
		} else {
			l_retpk.WriteShort(ERR_PT_SERVERBUSY);
			LG("ErrorServer", "account:%s ID:%d database operate failed:(%s)\n", ply->m_acctname.c_str(), ply->m_acctid, strPassword.c_str());
		}
	} else {
		l_retpk.WriteShort(ERR_PT_INVALID_PW2);
		LG("ErrorServer", "account:%s ID:%d wrong second password:(%s)\n", ply->m_acctname.c_str(), ply->m_acctid, strPassword.c_str());
	}
	return l_retpk;
}

WPacket GroupServerApp::TP_UPDATE_PASSWORD2(Player* ply, DataSocket* datasock, RPacket& pk) {
	WPacket l_retpk = GetWPacket();

	uShort old_len, new_len;
	const auto old_password = pk.ReadString(&old_len);
	const auto new_password = pk.ReadString(&new_len);

	if (ply->m_password == old_password && new_len <= ROLE_MAXSIZE_PASSWORD2) {
		auto db = GetDB();
		if (!db) {
			l_retpk.WriteShort(ERR_PT_SERVERBUSY);
			return l_retpk;
		}
		if (db->tblaccounts->UpdatePassword(ply->m_acctid, new_password)) {
			ply->m_password = new_password;
			l_retpk.WriteShort(ERR_SUCCESS);
		} else {
			l_retpk.WriteShort(ERR_PT_SERVERBUSY);
		}
	} else {
		l_retpk.WriteShort(ERR_PT_INVALID_PW2);
	}
	return l_retpk;
}

/*						char *l_str	=strstr(l_look,";");
						if(l_str)	*l_str=0;
						look.sTypeID	=atoi(l_look);
						l_look	=l_str+1;
						l_str	=strstr(l_look,";");
						for(int i=0;(l_str ||*l_look)&&(i<enumEQUIP_NUM);i++)
						{
							if(l_str)	*l_str=0;
							look.chState[i]	=atoi(l_look);
							if(l_str)
							{
								l_look	=l_str+1;
								l_str	=strstr(l_look,";");
							}else
							{
								l_look --;
							}
						}
						for(int i=0;(l_str ||*l_look)&&(i<enumEQUIP_NUM);i++)
						{
							if(l_str)	*l_str=0;
							look.sLink[i]	=atoi(l_look);
							if(l_str)
							{
								l_look	=l_str+1;
								l_str	=strstr(l_look,";");
							}else
							{
								l_look --;
							}
						}
*/
/*							char	l_tmpbuf[20];
							strcpy(l_look,itoa(look->sTypeID,l_tmpbuf,10));
							for(short i=0;i<enumEQUIP_NUM;i++)
							{
								strcat(l_look,";");
								strcat(l_look,itoa(look->chState[i],l_tmpbuf,10));
							}
							for(short i=0;i<enumEQUIP_NUM;i++)
							{
								strcat(l_look,";");
								strcat(l_look,itoa(look->sLink[i],l_tmpbuf,10));
							}
*/

void GroupServerApp::MP_GARNER2_UPDATE(Player* ply, DataSocket* datasock, RPacket& pk) {
	ORDERINFO orderinfo;
	// SYSTEMTIME st;time_t
	// GetLocalTime( &st);
	// time_t tt;
	// time(&tt);
	orderinfo.nid = pk.ReadLong();
	string strChaName = pk.ReadString();
	orderinfo.nlev = pk.ReadLong();
	string strjob = pk.ReadString();
	short sFightpoint = pk.ReadShort();

	if (strChaName.length() > common::conformity::character::name::max_length) {
		LG("Garner2", "order data exception\n");
		return;
	}
	strncpy_s(orderinfo.strname, sizeof(orderinfo.strname), strChaName.c_str(), _TRUNCATE);

	if (strjob.length() > 99) {
		LG("Garner2", "order data exception\n");
		return;
	}
	strncpy_s(orderinfo.strjob, sizeof(orderinfo.strjob), strjob.c_str(), _TRUNCATE);
	orderinfo.nfightpoint = (int)sFightpoint;

	auto db = GetDB();
	if (db) {
		db->tblparam->UpdateOrder(orderinfo);
	}
	CP_GARNER2_GETORDER(ply, datasock, pk);
}

void GroupServerApp::CP_GARNER2_GETORDER(Player* ply, DataSocket* datasock, RPacket& pk) {
	auto db = GetDB();
	if (!db) return;
	WPacket l_wpk = g_gpsvr->GetWPacket();
	ORDERINFO* porder;
	l_wpk.WriteCmd(CMD_PC_GARNER2_ORDER);
	for (int i = 0; i < MAXORDERNUM; i++) {
		porder = db->tblparam->GetOrderData(i);
		l_wpk.WriteString(porder->strname);
		l_wpk.WriteLong(porder->nlev);
		l_wpk.WriteString(porder->strjob);
		l_wpk.WriteLong(porder->nfightpoint);
	}
	g_gpsvr->SendToClient(ply, l_wpk);
}

// Add by sunny.sun 20090828
void GroupServerApp::MP_GM_BANACCOUNT(Player* ply, DataSocket* datasock, RPacket& pk) {
	string actName = pk.ReadString();
	WPacket l_wpk = g_gpsvr->GetWPacket();
	l_wpk.WriteCmd(CMD_PA_GMBANACCOUNT);
	l_wpk.WriteString(actName.c_str());
	g_gpsvr->SendData(g_gpsvr->m_acctsock, l_wpk);
}

void GroupServerApp::MP_GM_UNBANACCOUNT(Player* ply, DataSocket* datasock, RPacket& pk) {
	string actName = pk.ReadString();
	WPacket l_wpk = g_gpsvr->GetWPacket();
	l_wpk.WriteCmd(CMD_PA_GMUNBANACCOUNT);
	l_wpk.WriteString(actName.c_str());
	g_gpsvr->SendData(g_gpsvr->m_acctsock, l_wpk);
}

void GroupServerApp::MP_MUTE_PLAYER(Player* player, DataSocket* datasock, RPacket& pk) {
	const auto name = pk.ReadString();
	const auto time = pk.ReadLong();
	time > 0 ? player->EstopPlayer(name, time)
			 : player->DelEstopPlayer(name);
}
