/* Generated by Together */
#include "stdafx.h"
#include <iostream>
#include "IniFile.h"
#include "GroupServerApp.h"
#include "GameCommon.h"
#include "Team.h"
#include "Script.h"
#include "Parser.h"
#include "log.h"

using namespace std;

_DBC_USING

void InitDBSvrConnect(GroupServerApp& gpapp);
void InitACTSvrConnect(GroupServerApp& gpapp); // AccountServer连接

void GroupServerApp::Initialize() {

	// Sleep(20000);

	m_dwCheatCount = 0;
	// l_line<<newln<<"开始数据库连接"<<endln;
	LG("Connect", "begin connect database\n");
	InitDBSvrConnect(*this);
	{
		auto db = GetDB();
		db->tblguilds->InitAllGuilds(7);
	}
	const std::string l_acct = m_cfg["AccountServer"]["AcctEnable"];
	if (l_acct != "0") {
		// l_line<<newln<<"开始初始化AccountServer连接"<<endln;
		LG("Connect", "begin init AccountServer connect\n");
		InitACTSvrConnect(*this);
	}

	// LG("init", "初始化Lua Script...\n");
	LG("init", "init Lua Script...\n");
	if (!InitLuaScript()) {
		// THROW_EXCP(excp, "初始化LUA脚本失败！");
		throw std::runtime_error( "init LUA script failed!");
	}

	// 最后打开自己的端口侦听来自GateServer/GameServer的连接：
	// l_line<<newln<<"开始开始读取GroupServer.cfg配置文件"<<endln;
	LG("Connect", "begin read GroupServer.cfg\n");
	
	IniSection& l_is = m_cfg["Main"];
	const std::string l_ip = l_is["Listen_IP"];
	uShort l_port = std::stoi(l_is["Listen_Port"]);
	/*
		const_cha.MaxChaNum			=atoi(m_cfg["角色"]["每帐号最大角色数"]);
		const_cha.MaxChaNum			=min(const_cha.MaxChaNum,Player::emMaxCharacters);
		const_cha.MaxIconVal		=atoi(m_cfg["角色"]["个性化图标的最大值"]);
		const_cha.MaxLoginUsr		=atoi(m_cfg["角色"]["最大登录人数"]);
	*/
	const_cha.MaxChaNum = std::stoi(m_cfg["character"]["MaxCharacterNum"]);
	const_cha.MaxChaNum = min(const_cha.MaxChaNum, Player::emMaxCharacters);
	const_cha.MaxIconVal = std::stoi(m_cfg["character"]["MaxValue"]);
	const_cha.MaxLoginUsr = std::stoi(m_cfg["character"]["MaxPerson"]);

	/*
	const_frnd.InvitedMax		=atoi(m_cfg["好友"]["最多被邀请数"]);
	const_frnd.PendTimeOut		=atoi(m_cfg["好友"]["未决邀请超时"])*1000;
	const_frnd.FriendMax		=atoi(m_cfg["好友"]["每角色最多好友数"]);
	const_frnd.FriendGroupMax	=atoi(m_cfg["好友"]["每角色的自制好友分组数"]);
	*/
	const_frnd.InvitedMax = std::stoi(m_cfg["friend"]["MaxInvitedNum"]);
	const_frnd.PendTimeOut = std::stoi(m_cfg["friend"]["InvitedTime"]) * 1000;
	const_frnd.FriendMax = std::stoi(m_cfg["friend"]["MaxFriendNum"]);
	const_frnd.FriendGroupMax = std::stoi(m_cfg["friend"]["FriendGroupNum"]);

	/*
	const_team.InvitedMax		=atoi(m_cfg["组队"]["最多被邀请数"]);
	const_team.PendTimeOut		=atoi(m_cfg["组队"]["未决邀请超时"])*1000;
	const_team.MemberMax		=atoi(m_cfg["组队"]["每组队最多成员数"]);
	*/
	const_team.InvitedMax = std::stoi(m_cfg["team"]["MaxInvitedNum"]);
	const_team.PendTimeOut = std::stoi(m_cfg["team"]["InvitedTime"]) * 1000;
	const_team.MemberMax = std::stoi(m_cfg["team"]["MaxPersonNum"]);

	const_master.InvitedMax = 5;
	const_master.PendTimeOut = 30000;
	const_master.MasterMax = 1;
	const_master.PrenticeMax = 4;

	/*
	const_chat.MaxSession		=atoi(m_cfg["聊天"]["每玩家最多会话数"]);
	const_chat.MaxSession		=min(const_chat.MaxSession,Player::emMaxSessChat);
	const_chat.MaxPlayer		=atoi(m_cfg["聊天"]["每会话最多玩家数"]);
	const_chat.MaxPlayer		=min(const_chat.MaxPlayer,Player::emMaxSessPlayer);
	*/
	const_chat.MaxSession = std::stoi(m_cfg["chat"]["MaxChatNumPerPlayer"]);
	const_chat.MaxSession = min(const_chat.MaxSession, Player::emMaxSessChat);
	const_chat.MaxPlayer = std::stoi(m_cfg["chat"]["maxPlayerPerChat"]);
	const_chat.MaxPlayer = min(const_chat.MaxPlayer, Player::emMaxSessPlayer);

	/*
	const_interval.World		=atoi(m_cfg["聊天"]["世界频道说话间隔"])*1000;
	const_interval.Trade		=atoi(m_cfg["聊天"]["交易频道说话间隔"])*1000;
	const_interval.ToYou		=atoi(m_cfg["聊天"]["私聊频道说话间隔"])*1000;
	*/
	const_interval.World = std::stoi(m_cfg["chat"]["WorldInterval"]) * 1000;
	const_interval.Trade = std::stoi(m_cfg["chat"]["TradeInterval"]) * 1000;
	const_interval.ToYou = std::stoi(m_cfg["chat"]["ToYouInterval"]) * 1000;

	// Load IP whitelist security configuration
	LoadSecurityConfig();
	
	// Load maintenance mode configuration
	LoadMaintenanceConfig();

	if (!InitMasterRelation()) {
		// THROW_EXCP(excp, "初始化师徒关系表失败！");
		throw std::runtime_error(RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00001));
	}

	// l_line<<newln<<"开始装载ChaNameFilter.txt过虑文件"<<endln;
	LG("Connect", "begin load ChaNameFilter.txt\n");
	CTextFilter::LoadFile("ChaNameFilter.txt");
	// l_line<<newln<<"开始打开侦听端口:"<<l_port<<endln;
	LG("Connect", "begin listen port:%d\n", l_port);
	if (OpenListenSocket(l_port, l_ip.c_str())) {
		// THROW_EXCP(excpSock,l_ip<<","<<l_port<<" 打开失败！请检查端口"<<l_port<<"是否被占用或者GroupServer.cfg的Listen_IP参数配置是否正确。");
		char l_content[500];
		sprintf(l_content, RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00002), l_ip.c_str(), l_port, l_port);
		throw std::runtime_error(l_content);
	}
	// l_line<<newln<<"开始打开侦听端口:"<<l_port<<"成功完成，初始化过程结束"<<endln;
	LG("Connect", "open listen port:%d success, init is ok\n", l_port);
}

void InitDBSvrConnect(GroupServerApp& gpapp) {
	LG("group_sql", RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00030));

	const std::string l_ip = gpapp.m_cfg["Database"]["IP"];
	const std::string l_db = gpapp.m_cfg["Database"]["DB"];
	const std::string l_login = gpapp.m_cfg["Database"]["Login"];
	const std::string l_passwd = gpapp.m_cfg["Database"]["Password"];

	std::string l_errinfo;
	LG("group_sql", "begin connect database, ip = [%s], db = [%s]\n", l_ip.c_str(), l_db.c_str());
	if (!gpapp.m_cfg_db.connect(l_ip.c_str(), l_db.c_str(), l_login.c_str(), l_passwd.c_str(), l_errinfo)) {
		LG("group_sql", "connect database failed, error[%s]\n", l_errinfo.c_str());
		throw std::runtime_error( l_errinfo.c_str());
	}

	int poolSize = 4; // default pool size
	{
		const std::string poolSizeStr = gpapp.m_cfg["Database"]["PoolSize"];
		if (!poolSizeStr.empty()) poolSize = std::stoi(poolSizeStr);
	}
	LG("group_sql", "begin connect database pool, ip = [%s], db = [%s], poolSize = %d\n",
	   l_ip.c_str(), l_db.c_str(), poolSize);

	if (!gpapp.m_dbPool.Initialize(poolSize, l_ip.c_str(), l_db.c_str(),
	                                l_login.c_str(), l_passwd.c_str())) {
		LG("group_sql", "connect database pool failed\n");
		throw std::runtime_error("Database pool initialization failed");
	}

	LG("group_sql", "connect database pool ok, begin init datatable\n");

	// Use first connection for initialization checks (single-threaded at this point)
	DBConnection* initConn = gpapp.m_dbPool.GetConnectionDirect(0);

	// LG("group_sql", "开始检查 account表 完整性\n");
	LG("group_sql", "begin check table [account] \n");
	if (!initConn->tblaccounts->IsReady()) {
		// LG("group_sql", " account表 完整性检查失败\n");
		LG("group_sql", " check table [account] failed\n");
		// THROW_EXCP(excpDB,"触发器初始化失败");
		throw std::runtime_error(RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00003));
	}

	// LG("group_sql", "开始检查 公会表 完整性\n");
	LG("group_sql", "begin check table [guild]\n");
	if (!initConn->tblguilds->IsReady()) {
		// LG("group_sql", " 公会表 完整性检查失败\n");
		LG("group_sql", " check table [guild] failed \n");
		// THROW_EXCP(excpDB,"公会表尚未执行初始化SQL语句");
		throw std::runtime_error(RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00004));
	}
	initConn->tblcharaters->ZeroAddr();

	// LG("group_sql", "开始检查 param表 完整性\n");
	LG("group_sql", "begin check table [param]\n");

	if (initConn->tblparam->InitParam())
		LG("group_sql", "init database success\n");
}

void InitACTSvrConnect(GroupServerApp& gpapp) {
	gpapp.m_name = gpapp.m_cfg["Main"]["Name"];
	IniSection& l_is = gpapp.m_cfg["AccountServer"];
	const std::string l_passwd = l_is["Password"];
	const std::string l_ip = l_is["IP"];
	uShort l_port = std::stoi(l_is["Port"]);

	char buffer[512];

	while (!g_exit && !g_gpsvr->m_acctsock) {
		gpapp.m_acctsock = gpapp.Connect(l_ip.c_str(), l_port);
		if (!gpapp.m_acctsock) {
			// std::cout<<"连接AccountServer:("<<l_ip<<","<<l_port<<")失败,5秒后再次重连..."<<std::endl;
			memset(buffer, 0, sizeof(buffer));
			sprintf(buffer, RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00005), l_ip.c_str(), l_port);
			std::cout << buffer << std::endl;
			Sleep(5000);
			continue;
		}
		WPacket l_wpk = gpapp.GetWPacket();
		l_wpk.WriteCmd(CMD_PA_LOGIN);
		l_wpk.WriteString(gpapp.m_name.c_str());
		l_wpk.WriteString(l_passwd.c_str());
		RPacket l_rpk = gpapp.SyncCall(gpapp.m_acctsock, l_wpk);
		if (!l_rpk.HasData()) {
			// std::cout<<"在AccountServer:("<<l_ip<<","<<l_port<<")上登录超时,5秒钟后重新连接和登录..."<<std::endl;
			memset(buffer, 0, sizeof(buffer));
			sprintf(buffer, RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00006), l_ip.c_str(), l_port);
			std::cout << buffer << std::endl;
			gpapp.Disconnect(gpapp.m_acctsock, 0, 100);
			break;
		}
		if (l_rpk.ReadShort()) // 返回非0表示失败
		{
			// std::cout<<"在AccountServer:("<<l_ip<<","<<l_port<<")上登录失败,5秒钟后重新连接和登录..."<<std::endl;
			memset(buffer, 0, sizeof(buffer));
			sprintf(buffer, RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00007), l_ip.c_str(), l_port);
			std::cout << buffer << std::endl;
			gpapp.Disconnect(gpapp.m_acctsock, 0, 200);
			break;
		}
		gpapp.m_acctsock->SetPointer(0);
	}
}

// Helper function to trim whitespace from string
static std::string TrimWhitespace(const std::string& str) {
	size_t start = str.find_first_not_of(" \t\r\n");
	if (start == std::string::npos) return "";
	size_t end = str.find_last_not_of(" \t\r\n");
	return str.substr(start, end - start + 1);
}

void GroupServerApp::LoadSecurityConfig() {
	// Initialize defaults
	m_security.enabled = false;
	m_security.logRejected = true;
	m_security.allowedIPs.clear();
	
	// Always allow localhost
	m_security.allowedIPs.insert("127.0.0.1");
	m_security.allowedIPs.insert("::1");
	
	try {
		IniSection& secSection = m_cfg["Security"];
		
		// Check if whitelist is enabled
		const std::string enabledStr = secSection["WhitelistEnabled"];
		m_security.enabled = (enabledStr == "1" || enabledStr == "true" || enabledStr == "yes");
		
		// Check if we should log rejected connections
		const std::string logStr = secSection["LogRejectedConnections"];
		m_security.logRejected = (logStr != "0" && logStr != "false" && logStr != "no");
		
		// Parse allowed IPs (comma-separated)
		const std::string allowedIPsStr = secSection["AllowedIPs"];
		if (!allowedIPsStr.empty()) {
			size_t pos = 0;
			size_t nextPos;
			std::string ipList = allowedIPsStr;
			
			while ((nextPos = ipList.find(',', pos)) != std::string::npos) {
				std::string ip = TrimWhitespace(ipList.substr(pos, nextPos - pos));
				if (!ip.empty()) {
					m_security.allowedIPs.insert(ip);
				}
				pos = nextPos + 1;
			}
			// Add the last IP (or only IP if no commas)
			std::string lastIP = TrimWhitespace(ipList.substr(pos));
			if (!lastIP.empty()) {
				m_security.allowedIPs.insert(lastIP);
			}
		}
		
		// Log the security configuration
		if (m_security.enabled) {
			LG("Security", "[Security] IP Whitelist ENABLED with %d allowed IPs:\n", 
				(int)m_security.allowedIPs.size());
			std::cout << "[Security] IP Whitelist ENABLED with " << m_security.allowedIPs.size() 
					  << " allowed IPs:" << std::endl;
			
			for (const auto& ip : m_security.allowedIPs) {
				LG("Security", "  - %s\n", ip.c_str());
				std::cout << "  - " << ip << std::endl;
			}
		} else {
			LG("Security", "[Security] IP Whitelist DISABLED - accepting all connections\n");
			std::cout << "[Security] WARNING: IP Whitelist DISABLED - accepting all connections!" << std::endl;
		}
		
	} catch (...) {
		LG("Security", "[Security] No [Security] section in config, whitelist disabled\n");
		std::cout << "[Security] No [Security] section in config, whitelist disabled" << std::endl;
		m_security.enabled = false;
	}
}

bool GroupServerApp::IsIPAllowed(const char* ip) {
	if (!m_security.enabled) {
		return true; // Whitelist disabled, allow all
	}
	
	if (ip == nullptr || ip[0] == '\0') {
		return false;
	}
	
	std::string ipStr(ip);
	return m_security.allowedIPs.find(ipStr) != m_security.allowedIPs.end();
}

void GroupServerApp::LoadMaintenanceConfig() {
	// Initialize defaults
	m_maintenance.enabled = false;
	m_maintenance.kickOnEnable = true;
	m_maintenance.message = "Server is under maintenance. Please try again later.";
	
	try {
		IniSection& maintSection = m_cfg["Maintenance"];
		
		// Check if maintenance mode is enabled
		const std::string enabledStr = maintSection["Enabled"];
		m_maintenance.enabled = (enabledStr == "1" || enabledStr == "true" || enabledStr == "yes");
		
		// Check if we should kick players when enabling
		const std::string kickStr = maintSection["KickOnEnable"];
		m_maintenance.kickOnEnable = (kickStr != "0" && kickStr != "false" && kickStr != "no");
		
		// Get the maintenance message
		const std::string msgStr = maintSection["Message"];
		if (!msgStr.empty()) {
			m_maintenance.message = msgStr;
		}
		
		// Log the maintenance configuration
		if (m_maintenance.enabled) {
			LG("Maintenance", "[Maintenance] Mode ENABLED - Only HD accounts (GM level 30+) can login\n");
			std::cout << "[Maintenance] Mode ENABLED - Only HD accounts (GM level 30+) can login" << std::endl;
			std::cout << "[Maintenance] Message: " << m_maintenance.message << std::endl;
		} else {
			LG("Maintenance", "[Maintenance] Mode DISABLED - All accounts can login\n");
			std::cout << "[Maintenance] Mode DISABLED - All accounts can login" << std::endl;
		}
		
	} catch (...) {
		LG("Maintenance", "[Maintenance] No [Maintenance] section in config, disabled\n");
		std::cout << "[Maintenance] No [Maintenance] section in config, disabled" << std::endl;
		m_maintenance.enabled = false;
	}
}

bool GroupServerApp::IsMaintenanceMode() const {
	MutexArmor lock(m_maintenance.mtx);
	return m_maintenance.enabled;
}

void GroupServerApp::SetMaintenanceMode(bool enabled, bool kickNonGMs) {
	{
		MutexArmor lock(m_maintenance.mtx);
		m_maintenance.enabled = enabled;
	}
	
	if (enabled) {
		LG("Maintenance", "[Maintenance] Mode ENABLED by command\n");
		std::cout << "[Maintenance] Mode ENABLED - Only HD accounts (GM level 30+) can login" << std::endl;
		
		if (kickNonGMs) {
			KickAllNonGMPlayers("Server entering maintenance mode");
		}
	} else {
		LG("Maintenance", "[Maintenance] Mode DISABLED by command\n");
		std::cout << "[Maintenance] Mode DISABLED - All accounts can login" << std::endl;
	}
}

void GroupServerApp::KickAllNonGMPlayers(const char* reason) {
	int kickCount = 0;
	const char* kickReason = reason ? reason : m_maintenance.message.c_str();
	
	LG("Maintenance", "[Maintenance] Kicking all players below GM level 30...\n");
	std::cout << "[Maintenance] Kicking all players below GM level 30..." << std::endl;
	
	// Collect players to kick (avoid modifying list while iterating)
	struct KickInfo {
		uintptr_t gpAddr;
		uintptr_t gtAddr;
		DataSocket* gateSock;
	};
	std::vector<KickInfo> playersToKick;
	
	{
		RunChainGetArmor<Player> l(m_plylst);
		for (Player* ply = m_plylst.GetNextItem(); ply; ply = m_plylst.GetNextItem()) {
			if (ply->m_gm < 30 && ply->m_gate && ply->m_gtAddr) {
				DataSocket* gateSock = ply->m_gate->GetDataSock();
				if (gateSock) {
					playersToKick.push_back({MakeULong(ply), ply->m_gtAddr, gateSock});
				}
			}
		}
	}
	
	// Kick players outside the lock
	for (const auto& info : playersToKick) {
		// Send disconnect to GateServer via the player's gate connection
		KickUser(info.gateSock, info.gpAddr, info.gtAddr);
		kickCount++;
	}
	
	LG("Maintenance", "[Maintenance] Kicked %d players (GM level < 30)\n", kickCount);
	std::cout << "[Maintenance] Kicked " << kickCount << " players (GM level < 30)" << std::endl;
}

