/* Generated by Together */
#include "stdafx.h"
#include "Master.h"
#include "GroupServerApp.h"

int Master::GetInvitedMax() {
	return g_gpsvr->const_master.InvitedMax;
}
void Master::InvitedCheck(Invited* invited) {
	MasterInvitedCheck(invited);
}
