print("------------------------------------")
print("-- Loading hell3 file             --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_hell3()
	return 245,75
end

function init_entry(map)
	SetMapEntryMapName(map, "hell2")
	SetMapEntryTime(map, "2007/1/19/15/0", "1/0/0", "0/1/0", "0/6/0")
end

function after_enter_hell3(role, map_copy)
	SystemNotice(role, "Mysterious voice: "..GetChaDefaultName(role)..", this is your last stop and also your place of burial. Enjoy your last moments while you can!") 
end

function before_leave_hell3(role)
end

function map_copy_first_run_hell3(map_copy)
end

function AbaddonSpecialSkill(varID)
	if varID == 10 then
		MapCopyNotice(map_copy, "Phantom Baron: Draw blood! Phantom Sword!")
		SetCharaAttr((GetChaAttr(Abaddon.Boss[varID].Role, ATTR_BMSPD) * 4), Abaddon.Boss[varID].Role, ATTR_BMSPD)
	end
	if varID == 11 then
		MapCopyNotice(map_copy, "Demon Flame: Burn with the flames of hell!")
		SetCharaAttr(10000, Abaddon.Boss[varID].Role, ATTR_BCRT)
	end
	if varID == 12 then
		MapCopyNotice(map_copy, "Evil Beast: I will unleash all of my anger towards you!")
		SetCharaAttr((GetChaAttr(Abaddon.Boss[varID].Role, ATTR_BMNATK) * 2), Abaddon.Boss[varID].Role, ATTR_BMNATK)
		SetCharaAttr((GetChaAttr(Abaddon.Boss[varID].Role, ATTR_BMXATK) * 2), Abaddon.Boss[varID].Role, ATTR_BMXATK)
	end
	if varID == 13 then
		MapCopyNotice(map_copy, "Tyran: Try to defeat me now that I have increased my defense, hahah!")
		SetCharaAttr((GetChaAttr(Abaddon.Boss[varID].Role, ATTR_BDEF) * 2), Abaddon.Boss[varID].Role, ATTR_BDEF)
	end
	if varID == 14 then
		MapCopyNotice(map_copy, "Phoenix: Soar to the skies, wing of Phoenix!")
		SetCharaAttr((GetChaAttr(Abaddon.Boss[varID].Role, ATTR_BASPD) * 2), Abaddon.Boss[varID].Role, ATTR_BASPD)
	end
	if varID == 15 then
		MapCopyNotice(map_copy, "Despair: Suffer, while all hope dies!")
		SetCharaAttr((GetChaAttr(Abaddon.Boss[varID].Role, ATTR_BMXHP) * 2), Abaddon.Boss[varID].Role, ATTR_HP)
	end
	if varID == 16 then
		MapCopyNotice(map_copy, "Drakan: Awaken all of my servants!")
		local PosX, PosY = GetChaPos(Abaddon.Boss[varID].Role)
		local Monster1, Monster2, Monster3 = {}, {}, {}
		for i = 1, 20, 1 do
			CreateCha(827,(PosX + 100),(PosY + 700), 145, 21600)
			CreateCha(828,(PosX + 700),(PosY + 700), 145, 21600)
			CreateCha(828,(PosX - 700),(PosY - 700), 145, 21600)
		end
	end
	if varID == 17 then
		MapCopyNotice(map_copy, "Tidal: Awaken, wave of hell!!")
		local PosX, PosY = GetChaPos(Abaddon.Boss[varID].Role)
		local new1 = CreateCha(986,(PosX + 100),(PosY + 700), 145, 21600)
		local new2 = CreateCha(986,(PosX + 700),(PosY + 700), 145, 21600)
		local new3 = CreateCha(986,(PosX - 700),(PosY - 700), 145, 21600)
		SetCharaAttr(1000000, new1, ATTR_HP)
		SetCharaAttr(1000000, new1, ATTR_HP)
		SetCharaAttr(1000000, new1, ATTR_HP)
	end
end

function map_copy_run_hell3(map_copy)
	for i = 10, 17, 1 do
		if Abaddon.Boss[i].Check == 0 then
			Abaddon.Boss[i].Role = CreateCha(Abaddon.Boss[i].ID, Abaddon.Boss[i].X, Abaddon.Boss[i].Y, 145, Abaddon.Boss[i].Life)
			Abaddon.Boss[i].Check = 1
		end
		if(GetChaAttr(Abaddon.Boss[i].Role, ATTR_HP)/GetChaAttr(Abaddon.Boss[i].Role, ATTR_MXHP)) <= 0.5 and Abaddon.Boss[i].Skill[1] == 0 then
			AbaddonSpecialSkill(map_copy, i)
			Abaddon.Boss[i].Skill[1] = 1
		end
		if Abaddon.Boss[i].Check == 1 and CheckMonsterDead(Abaddon.Boss[i].Role) == 1 then
			Abaddon.Boss[i].Check = 2
			Abaddon.Tick = Abaddon.Tick + 1
			MapCopyNotice(map_copy, Abaddon.Boss[i].Message)
		end
	end
	if Abaddon.Tick == 17 then
		if Abaddon.Time[10] == 0 then
			MapCopyNotice(map_copy, "Warning:[Abaddon Haven] has collapsed!")
			CloseMapEntry("hell3")
			CloseMapCopy("hell3")
		elseif Abaddon.Time[10] <= 15 then
			MapCopyNotice(map_copy, "Warning:[Abaddon Haven] will collapse in "..Abaddon.Time[10].." second(s)!")
		elseif Abaddon.Time[10] == 180 then
			MapCopyNotice(map_copy, "Mysterious Voice: I admire your ability. Even the 8 Abyss Lords also cowered in defeat. Come forth to me as you have awakened my blood-lust! This dimension will vanish and you will have nowhere to hide! Do not disappoint me!")
		elseif(Abaddon.Time[10] - math.floor(Abaddon.Time[10]/60)*60) == 0 and Abaddon.Time[10] <= 180 then
			MapCopyNotice(map_copy, "Warning:[Abaddon Haven] will collapse in "..(Abaddon.Time[10]/60).." minute(s)!")
		end
		Abaddon.Time[10] = Abaddon.Time[10] - 1
	end
end

function map_copy_run_special_hell3(map)
end

function map_run_hell3(map)
end

function map_copy_close_hell3(map_copy)
	ClearAllSubMapCha(map_copy)
	ClearAllSubMapMonster(map_copy)
end

function map_copy_before_close_hell3(map_copy)
end

function can_open_entry_hell3(map)
	return 1
end