print("-- [Loading] System SDK")

Server = {}
Server.Sys = {}
Server.Sys.Maps = {}
Server.Sys.Level = {}
Server.Sys.Player = {}
Server.Sys.Bank = {}
Server.Sys.Apparel = {}
Server.Sys.Fairy = {}
Server.Sys.Gold = {}
Server.Sys.Socket = {}
Server.Sys.Rates = {}
Server.Sys.Rates.Global = {}
Server.Sys.Rates.Hour = {}
Server.Sys.Rates.Day = {}
Server.Sys.Rates.Map = {}
Server.Sys.Rates.Level = {}
Server.Sys.Rates.Class = {}
Server.Sys.Ranking = {}
Server.Sys.Ticket = {}
Server.Sys.BlackDragonAltar = {}
Server.Maps = {}
Server.Teleport = {}
Server.Level = {}
Server.Bank = {}
Server.Equipment = {}
Server.Equipment.Upgrade = {}
Server.Socket = {}
Server.Rates = {}
Server.Rates.Global = {}
Server.Rates.Map = {}
Server.Rates.Modifier = {}
Server.Rates.Day = {}
Server.Player = {}
Server.Player.Skill = {}
Server.Fairy = {}
Server.Fairy.ID = {}
Server.Fairy.Level = {}
Server.Fairy.AutoFeed = {}
Server.Fairy.Ration = {}
Server.Fairy.Fruits = {}
Server.Fairy.Possession = {}
Server.Fairy.Possession.Skill = {}
Server.Fairy.Effect = {}
Server.Fairy.Marriage = {}
Server.Fairy.Egg = {}
Server.Fairy.Fruit = {}
Server.Fairy.Skill = {}
Server.Fairy.Funny = {}
Server.Fairy.Funny.Skill = {}
Server.Life = {}
Server.Life.Skill = {}
Server.Gold = {}
Server.AltarBD = {}
Server.AltarBD.Trib = {}
Server.AltarBD.Dice = {}
Server.AltarBD.Power = {}
Server.AltarBD.Power[267] = ITEMATTR_VAL_STR
Server.AltarBD.Power[268] = ITEMATTR_VAL_AGI
Server.AltarBD.Power[269] = ITEMATTR_VAL_DEX
Server.AltarBD.Power[270] = ITEMATTR_VAL_CON
Server.AltarBD.Trib[1] = {Gem = 866, Equipment = 845}
Server.AltarBD.Trib[2] = {Gem = 865, Equipment = 847}
Server.AltarBD.Trib[3] = {Gem = 864, Equipment = 846}
Server.Sys.MasterAccount = {}
Server.Sys.Maps["Dream Island"] = {}
Server.Sys.Maps["Chaos Argent"] = {}
Server.Sys.Maps["Forsaken City"] = {}
Server.Sys.Maps["Dark Swamp"] = {}
Server.Sys.Maps["Demonic World"] = {}
Server.Sys.Maps["garner2"] = {}
Server.Sys.Maps["PKmap"] = {}
Server.Sys.Maps["secretgarden"] = {}
Server.Cloak = {}
Server.Cloak.Item = {}
Server.Cloak.Level = {}
Server.Cloak.Rate = {}
Server.Restore = {}
Server.Restore.Life = {}
Server.Restore.Attr = {}
Server.EqSet = {}