print("------------------------------------")
print("-- Loading hell4 file             --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_hell4()
	return 191,180
end

function init_entry(map)
    SetMapEntryMapName(map, "hell3")
    SetMapEntryTime(map, "2007/1/20/0/0", "1/0/0", "0/1/0", "0/3/0")
end

function after_enter_hell4(role, map_copy)
	SystemNotice(role, "Mysterious voice: "..GetChaDefaultName(role)..", I will let you behold the real power of Death!") 
end

function before_leave_hell4(role)
end

function map_copy_first_run_hell4(map_copy)
end

function map_copy_run_hell4(map_copy)
	if Abaddon.Boss[18].Check == 0 then
		Abaddon.Boss[18].Role = CreateCha(Abaddon.Boss[18].ID, Abaddon.Boss[18].X, Abaddon.Boss[18].Y, 145, Abaddon.Boss[18].Life)
		Abaddon.Boss[18].Check = 1
	end
	if Abaddon.Boss[18].Check == 1 and CheckMonsterDead(Abaddon.Boss[18].Role) == 1 then
		Abaddon.Boss[18].Check = 2
		Abaddon.Tick = Abaddon.Tick + 1
		MapCopyNotice(map_copy, Abaddon.Boss[18].Message)
	end
	if Abaddon.Tick == 18 then
		if Abaddon.Time[18] == 0 then
			MapCopyNotice(map_copy, "Warning: [Abaddon 18] has collapsed!")
			CloseMapEntry("hell4")
			CloseMapCopy("hell4")
		elseif Abaddon.Time[18] <= 15 then
			MapCopyNotice(map_copy, "Warning: [Abaddon 18] will collapse in "..Abaddon.Time[18].." second(s)!")
		elseif Abaddon.Time[18] == 120 then
			MapCopyNotice(map_copy, "Mysterious Voice: Ha-ha! At least there is somebody worthy of my challenge! Only Death awaits you! Let the game begin!")
		elseif(Abaddon.Time[18] - math.floor(Abaddon.Time[18]/60)*60) == 0 and Abaddon.Time[18] <= 120 then
			MapCopyNotice(map_copy, "Warning: [Abaddon 18] will collapse in "..(Abaddon.Time[18]/60).." minute(s)!")
		end
		Abaddon.Time[18] = Abaddon.Time[18] - 1
	end
end

function map_copy_run_special_hell4(map)
end

function map_run_hell4(map)
end

function map_copy_close_hell4(map_copy)
end

function map_copy_before_close_hell4(map_copy)
end

function can_open_entry_hell4(map)
	return 1
end 
