//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 Ambient;
//   float4 Base;
//   float4 BonePalette[150];
//   float4 Diffuse;
//   float4 LightDir;
//   float4x4 ViewProj;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Base         c0       1
//   ViewProj     c1       4
//   LightDir     c5       1
//   Ambient      c6       1
//   Diffuse      c7       1
//   BonePalette  c21    150
//

    vs_2_x
    def c8, 0.300000012, 0.449999988, 0.25, 0.699999988
    def c9, 1, 0, 0.400000006, 0.75
    def c10, 0.920000017, 0.959999979, 1.04999995, 0
    def c11, 0.119999945, 0.0400000215, -0.0999999642, 0.100000001
    def c12, 0, -0.44721359, 0.89442718, 0
    def c13, 2, 1.86000001, 1.60000002, 0
    def c14, 1.5, 1.45500004, 1.3499999, 0
    dcl_position v0
    dcl_blendindices v1
    dcl_normal v2
    dcl_texcoord v3
    mul r0.x, v1.z, c0.w
    frc r0.y, r0.x
    add r0.z, r0.x, -r0.y
    slt r0.y, -r0.y, r0.y
    slt r0.x, r0.x, -r0.x
    mad r0.x, r0.x, r0.y, r0.z
    mova a0.x, r0.x
    mad r0, v0.xyzx, c9.xxxy, c9.yyyx
    dp4 r1.x, r0, c21[a0.x]
    dp4 r1.y, r0, c22[a0.x]
    dp4 r1.z, r0, c23[a0.x]
    mov r1.w, c9.x
    dp4 oPos.x, r1, c1
    dp4 oPos.y, r1, c2
    dp4 oPos.z, r1, c3
    dp4 oPos.w, r1, c4
    dp3 r0.x, v2, c21[a0.x]
    dp3 r0.y, v2, c22[a0.x]
    dp3 r0.z, v2, c23[a0.x]
    nrm r1.xyz, r0
    mov r0.xyz, c12
    add r0.xyz, r0, c5
    nrm r2.xyz, r0
    dp3 r0.x, r1, r2
    max r0.x, r0.x, c9.y
    sge r0.x, r0.x, c8.w
    dp3 r0.y, r1, c5
    dp3 r0.z, r1, c12
    max r0.yz, r0, c9.y
    add r0.z, -r0.z, c9.x
    sge r0.z, r0.z, c11.w
    sge r0.yw, r0.y, c9.xzzw
    mul r0.x, r0.w, r0.x
    mul r1.xyz, r0.x, c14
    mad r0.x, r0.y, c8.x, c8.y
    mad r0.x, r0.w, c8.z, r0.x
    mov r2.xyz, c6
    mad r2.xyz, c7, r0.x, r2
    mov r3.xyz, c11
    mad r0.xyw, r0.x, r3.xyzz, c10.xyzz
    mad r0.xyw, r2.xyzz, r0, r1.xyzz
    mad oD0.xyz, r0.z, c13, r0.xyww
    mov oD0.w, c6.w
    mov oT0.xy, v3

// approximately 48 instruction slots used
