/* Generated by Together */
#pragma once
/**
 * @persistent
 */
#pragma pack(push)
#pragma pack(4)

extern const float g_sin[91];
extern const float g_cos[91];
extern const float g_tan[90];

//	namespace	GAME
//{
struct Point {
	Point() = default;
	Point(int px, int py) : x(px), y(py) {}
	void move(short dir, int distance);

	int x{};
	int y{};
};
struct Square {
	Point centre;
	int radius{};
};
struct Circle {
	Point centre;
	int radius{};
};
struct Rect {
	Point ltop; // 左上角
	Point rbtm; // 右下角
	int width() const { return rbtm.x - ltop.x; }
	int height() const { return rbtm.y - ltop.y; }
};
void eddy(int x, int y, short dir, int radius, int& retx, int& rety);
short arctan(const Point& src, const Point& dest);	// 从src到dest得方向夹角
bool operator^(const Square& S1, const Square& S2); // 相交函数
bool operator^(const Circle& C1, const Circle& C2); // 相交函数
bool operator^(const Rect& R1, const Rect& R2);		// 相交函数

inline bool operator==(const Point& P1, const Point& P2) {
	return (P1.x == P2.x) && (P1.y == P2.y);
}
inline bool operator==(const Square& S1, const Square& S2) {
	return (S1.centre == S2.centre) && (S1.radius == S2.radius);
}
inline bool operator==(const Circle& C1, const Circle& C2) {
	return (C1.centre == C2.centre) && (C1.radius == C2.radius);
}
inline bool operator==(const Rect& R1, const Rect& R2) {
	return (R1.ltop == R2.ltop) && (R1.rbtm == R2.rbtm);
}
//	}	//	namespace	GAME
#pragma pack(pop)
