print("------------------------------------")
print("-- Loading jialebi file           --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 1)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 0)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 1)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_jialebi()
	return 0,0
end

function init_entry(map)
end

function after_enter_jialebi(role, map_copy)
end

function before_leave_jialebi(role)
end

function map_copy_first_run_jialebi(map_copy)
end

function map_copy_run_jialebi(map_copy)
end

function map_copy_run_special_jialebi(map)
end

function map_run_jialebi(map)
end

function map_copy_close_jialebi(map_copy)
end

function map_copy_before_close_jialebi(map_copy)
end

function can_open_entry_jialebi(map)
	return 1
end