print("------------------------------------")
print("-- Loading hell2 file             --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_hell2()
	return 72,179
end

function init_entry(map)
	SetMapEntryMapName(map, "hell")
	SetMapEntryTime(map, "2007/1/19/15/0", "1/0/0", "0/1/0", "0/6/0")
end

function after_enter_hell2(role, map_copy)
	SystemNotice(role, "Mysterious voice: "..GetChaDefaultName(role)..", not bad to be able to survive till here. If you can cross the water in front, I'll acknowledge your capabilities!") 
end

function before_leave_hell2(role)
end

function map_copy_first_run_hell2(map_copy)
end

function map_copy_run_hell2(map_copy)
	if Abaddon.Boss[9].Check == 0 then
		Abaddon.Boss[9].Role = CreateCha(Abaddon.Boss[9].ID, Abaddon.Boss[9].X, Abaddon.Boss[9].Y, 145, Abaddon.Boss[9].Life)
		Abaddon.Boss[9].Check = 1
	end
	if Abaddon.Boss[9].Check == 1 and CheckMonsterDead(Abaddon.Boss[9].Role) == 1 then
		Abaddon.Boss[9].Check = 2
		Abaddon.Tick = Abaddon.Tick + 1
		MapCopyNotice(map_copy, Abaddon.Boss[9].Message)
	end
	if Abaddon.Tick == 9 then
		if Abaddon.Time[9] == 0 then
			MapCopyNotice(map_copy, "Warning:[Abaddon 9] has collapsed!")
			CloseMapEntry("hell2")
			CloseMapCopy("hell2")
		elseif Abaddon.Time[9] <= 15 then
			MapCopyNotice(map_copy, "Warning:[Abaddon 9] will collapse in "..Abaddon.Time[9].." second(s)!")
		elseif Abaddon.Time[9] == 240 then
			MapCopyNotice(map_copy, "Mysterious Voice: Not bad, warriors. You even managed to kill my last pet. But do you remember what happen previously?")
		elseif(Abaddon.Time[9] - math.floor(Abaddon.Time[9]/60)*60) == 0 and Abaddon.Time[9] <= 240 then
			MapCopyNotice(map_copy, "Warning:[Abaddon 9] will collapse in "..(Abaddon.Time[9]/60).." minute(s)!")
		end
		Abaddon.Time[9] = Abaddon.Time[9] - 1
	end
end

function map_copy_run_special_hell2(map)
end

function map_run_hell2(map)
end

function map_copy_close_hell2(map_copy)
	ClearAllSubMapCha(map_copy)
	ClearAllSubMapMonster(map_copy)
end

function map_copy_before_close_hell2(map)
end

function can_open_entry_hell2(map)
	return 1
end