print("------------------------------------")
print("-- Loading puzzleworld file       --")
print("------------------------------------")
print("-- [Loading] ctrl.lua" )

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_puzzleworld()
	return 910,1069
end

function init_entry(map)
    SetMapEntryMapName(map, "garner")
    SetMapEntryTime(map, "2005/8/30/2/0", "0/4/0", "0/0/40", "0/2/0")
end

function after_enter_puzzleworld(role, map_copy)
end

function before_leave_puzzleworld(role)
end

function map_copy_first_run_puzzleworld(map_copy)
end

function map_copy_run_puzzleworld(map_copy)
end

function map_copy_run_special_puzzleworld(map)
end

function map_run_puzzleworld(map)
end

function map_copy_close_puzzleworld(map_copy)
end

function map_copy_before_close_puzzleworld(map_copy)
end

function can_open_entry_puzzleworld(map)
	local Hour = GetNowTime()
	if Hour == 02 or Hour == 06 or Hour == 10 or Hour == 14 or Hour == 18 or Hour == 22 then
		return 1
	end
	return 0
end