/* Generated by Together */
#include "stdafx.h"
#ifndef USE_IOCP

#include "GameServerApp.h"
#include <iostream>
#include <time.h>
#include "GameCommon.h"
#include "SubMap.h"
#include "GameApp.h"
#include "TryUtil.h"
#include "OfflineStall.h"

_DBC_USING
// 不要修改下面的行,谢谢合作!
uLong NetBuffer[] = {100, 10, 0};
bool g_logautobak = true;
// End

extern volatile BOOL g_bGameEnd; // GameServer 退出全局标志

// 连接 GateServer 任务类
int ConnectGateServer::Process() {
	T_B
		DWORD dwTick,
		dwCurTick;
	DWORD dwInterval = 5000;
	DWORD dwConnectTick = 0;

	dwTick = dwCurTick = GetTickCount();
	dwTick -= dwConnectTick; // 保证线程运行后立即执行连接GateServer的操作

	while (!GetExitFlag()) {
		dwCurTick = GetTickCount();

		static DWORD dwLastRunTick = 0;
		if (dwCurTick - dwLastRunTick < dwInterval) {
			Sleep(10);
			continue;
		}

		dwLastRunTick = dwCurTick;

		// 对未连接的 GateServer 进行连接
		if (dwCurTick - dwTick >= dwConnectTick) {
			dwTick = dwCurTick;
			for (int i = 0; i < m_gmsvr->m_gtnum; i++)
				if (!m_gmsvr->m_gtarray[i].IsValid())
					m_gmsvr->ConnectGate(&m_gmsvr->m_gtarray[i]);
		}
	}

	return 0;
	T_E
}

// 监听InfoServer线程
int ToInfoServer::Process() {
	T_B if (m_gmsvr->m_IfServer.GetPort() == 0) {
		// LG("Store_data", "没有配置InfoServer!\n");
		LG("Store_data", "not configure InfoServer!\n");
		return 0;
	}

	m_gmsvr->m_IfServer.InValid();
	LG("Store_data", "Connect InfoServer(%s, %d)...\n", m_gmsvr->m_IfServer.GetIP().c_str(), m_gmsvr->m_IfServer.GetPort());
	g_gmsvr->ConnectInfo(&m_gmsvr->m_IfServer);

	DWORD dwCurTick;
	DWORD dwInterval = m_dwTimeOut;

	dwCurTick = GetTickCount();

	// 登录InfoServer
	while (!GetExitFlag()) {
		dwCurTick = GetTickCount();

		static DWORD dwLastRunTick = 0;
		if (dwCurTick - dwLastRunTick < dwInterval) {
			Sleep(10);
			continue;
		}

		try {
			if (!m_gmsvr->m_IfServer.IsValid() && m_gmsvr->m_IfServer.IsConnect()) {
				LG("Store_data", "Login InfoServer...\n");
				m_gmsvr->m_IfServer.Login();
			}
		} catch (...) {
			LG("Store_data", "Process Error!\n");
		}

		dwLastRunTick = dwCurTick;
	}

	LG("Store_data", "ToInfoServer Process Out!\n");

	return 0;
	T_E
}

void InfoServer::Login() {
	T_B
		pNetMessage pNm = new NetMessage();
	char szPwd[33];
	cChar* szPassword = (cChar*)GetPassword();
	if (strlen(szPassword) > 32) {
		LG("Store_data", "Login password too int!\n");
		return;
	}
	strcpy(szPwd, szPassword);
	BuildNetMessage(pNm, INFO_LOGIN, 0, 0, 0, (unsigned char*)szPwd, int(strlen(szPwd) + 1));
	g_gmsvr->GetInfoServer()->SendData(pNm);
	FreeNetMessage(pNm);
	T_E
}

int InfoServer::PeekMsg(unsigned int ms) {
	T_B
		// 至少处理10条消息
		if (ms < 10)
			ms = 10;

	while (ms-- > 0) {
		if (!m_MsgQueue.IsEmpty()) {
			pNetMessage msg = m_MsgQueue.Pop();
			g_gmsvr->ProcessData(msg, CMD_FM_MSG);
		} else
			break;
	}
	return 0;
	T_E
}

void InfoServer::OnConnect(bool result) {
	if (result) {
		LG("Store_data", "InfoServer Connected!\n");
		g_gmsvr->ProcessData(nullptr, CMD_FM_CONNECTED);
	} else {
		LG("Store_data", "InfoServer Connect Failed!\n");

		try {
			// g_gmsvr->DisconnectInfo(this);
		} catch (...) {
			LG("Store_data", "OnConnect Error!\n");
		}
	}
}

void InfoServer::OnDisconnect() {
	InValid();
	LG("Store_data", "InfoServer Disconnected!\n");

	try {
		// g_gmsvr->DisconnectInfo(this);
	} catch (...) {
		LG("Store_data", "OnDisconnect Error!\n");
	}

	g_gmsvr->ProcessData(nullptr, CMD_FM_DISCONNECTED);
}

// 网络通信应用类
GameServerApp::GameServerApp(ThreadPool* proc, ThreadPool* comm)
	: TcpClientApp(this, proc, comm), RPCMGR(this), m_count(0), PKQueue(false) {
	T_B
		// LG("init", "开始构造ServerApp\n");
		LG("init", "start init ServerApp\n");

	// 初始化随机数种子
	srand((unsigned)time(nullptr));

	// 得到此 GameServer 的网络名称
	m_strGameName = g_Config.m_szName;

	// 初始化 GateServer 数组
	m_gtnum = std::min<decltype(m_gtnum)>(MAX_GATE, g_Config.m_nGateCnt);
	for (int i = 0; i < m_gtnum; ++i) {
		m_gtarray[i].GetIP() = g_Config.m_szGateIP[i];
		m_gtarray[i].GetPort() = g_Config.m_nGatePort[i];
		m_gtarray[i].m_playerlist = nullptr;
	}

	// 初始化InfoServer
	m_IfServer.SetInfoServer(g_Config.m_szInfoIP, g_Config.m_nInfoPort, g_Config.m_szInfoPwd, g_Config.m_nSection);

	// 初始化 连接断开锁， 防止对一个 Socket 执行两次 Disconnect
	m_mutdisconn.Create(false);

	// 网络设置
	SetPKParse(0, 2, 32 * 1024, 400);
	BeginWork(g_Config.m_lSocketAlive);

	// LG("init", "ServerApp构造结束\n");
	LG("init", "ServerApp init over\n");
	T_E
}

GameServerApp::~GameServerApp() {
	T_B if (m_IfServer.IsConnect()) {
		DisconnectInfo(&m_IfServer);
		LG("Store_data", "Disconnect InfoServer!\n");
	}

	ShutDown(2 * 1000);
	T_E
}

// 返回值:true-允许连接,false-不允许连接
bool GameServerApp::OnConnect(DataSocket* datasock) {
	T_B
		datasock->SetRecvBuf(64 * 1024);
	datasock->SetSendBuf(64 * 1024);

	LG("Connect", "GateServer Connected! IP = [%s] port = %d\n", datasock->GetPeerIP(), datasock->GetPeerPort());
	return true;
	T_E
}

// reason值:0-本地程序正常退出；-3-网络被对方关闭；-1-Socket错误;-5-包长度超过限制.
void GameServerApp::OnDisconnect(DataSocket* datasock, int reason) {
	T_B
		LG("Connect", "GateServer Disconnect! IP = [%s] port = %d, reason = [%s]\n", datasock->GetPeerIP(), datasock->GetPeerPort(), GetDisconnectErrText(reason).c_str());

	GateServer* gt = (GateServer*)datasock->GetPointer();
	if (gt == nullptr)
		return;

	// TODO(Ogge): Check how this actually work:
	//  GateServer::IsValid() will return true until the packet CMD_MM_GATE_RELEASE has been processed
	//  Could this function be called n-times and in turn send this packet n-times before its actually invalidated
	if (!gt->IsValid())
		return;
	m_mutdisconn.lock();
	do {
		// dual-check
		if (!gt->IsValid())
			break;

		// 通知逻辑层与该Gate的连接断开
		WPacket pkt = GetWPacket();
		pkt.WriteCmd(CMD_MM_GATE_RELEASE);
		pkt.WriteLongLong(MakeULong(gt->m_playerlist));
		auto rpkt = RPacket(pkt);
		AddPK(datasock, rpkt);

		// 清理GateServer
		// gt->Invalid(); // 放到外层操作（CGameApp::OnGateDisconnect处）

	} while (false);
	m_mutdisconn.unlock();

	T_E
}

void GameServerApp::OnProcessData(DataSocket* datasock, RPacket& pk) {
	T_B
		AddPK(datasock, pk);
	T_E
}

void GameServerApp::ProcessData(DataSocket* datasock, RPacket& pk) {
	T_B if (datasock == nullptr) return;
	GateServer* gt = (GateServer*)datasock->GetPointer();
	if (gt == nullptr)
		return;

	int msg_id;
	uShort cmd = pk.ReadCmd();
	switch (cmd) {
	case CMD_MM_GATE_CONNECT:
		LG("Connect", "ProcessData Gate_Connect\n");
		msg_id = NETMSG_GATE_CONNECTED;
		break;

	case CMD_MM_GATE_RELEASE:
		msg_id = NETMSG_GATE_DISCONNECT;
		break;

	default:
		msg_id = NETMSG_PACKET;
		break;
	}

	g_pGameApp->ProcessNetMsg(msg_id, gt, pk);
	T_E
}

void GameServerApp::ProcessData(pNetMessage msg, short sType) {
	T_B switch (sType) {
	case InfoServer::CMD_FM_CONNECTED:
		break;

	case InfoServer::CMD_FM_DISCONNECTED:
		break;

	case InfoServer::CMD_FM_MSG:
		break;

	default:
		break;
	}

	g_pGameApp->ProcessInfoMsg(msg, sType, GetInfoServer());
	T_E
}

WPacket GameServerApp::OnServeCall(DataSocket* datasock, RPacket& pk) {
	T_B
		uShort l_cmd = pk.ReadCmd();
	switch (l_cmd) {
	case CMD_TM_KICKCHA:
		return TM_KICKCHA(datasock, pk);
	case CMD_TM_OFFLINE_MODE:
		return TM_OFFLINE_MODE(datasock, pk);
	}
	return 0;
	T_E
}

WPacket GameServerApp::TM_KICKCHA(DataSocket* datasock, RPacket& pkt) {
	WPacket l_retpk = GetWPacket();

	int lChaDbID = READ_LONG(pkt);
	CPlayer* pCOldPly = g_pGameApp->FindPlayerByDBChaID(lChaDbID);
	if (!pCOldPly || !pCOldPly->IsValid()) {
		l_retpk.WriteChar(0);
	} else {
		pCOldPly->GetCtrlCha()->BreakAction();
		pCOldPly->MisLogout();
		pCOldPly->MisGooutMap();
		g_pGameApp->ReleaseGamePlayer(pCOldPly);
		l_retpk.WriteChar(1);
	}
	return l_retpk;
}

dbc::WPacket GameServerApp::TM_OFFLINE_MODE(dbc::DataSocket* datasock, RPacket& rpk) {
	LG("offline_stall", "TM_OFFLINE_MODE handler called\n");
	
	// GateServer writes: [GatePlayerAddr][GameServerPlayerAddr]
	// ReverseRead reads from END of packet, so we read in reverse order:
	auto player = (CPlayer*)MakePointer(rpk.ReverseReadLongLong());  // gm_addr - GameServer's player
	auto gatePlayerAddr = rpk.ReverseReadLongLong();                  // GateServer's player address
	CCharacter* pCCha{};

	LG("offline_stall", "TM_OFFLINE_MODE: player=%p, gateAddr=%llu\n", player, gatePlayerAddr);

	auto wpk = GETWPACKET();
	
	const auto return_code = [&] {
		// Use registry validation instead of just address check
		if (!ValidatePlayerPointer(player, gatePlayerAddr)) {
			LG("offline_stall", "TM_OFFLINE_MODE: Invalid player %p or gateAddr mismatch\n", player);
			return ReturnCode::OfflineMode::Unknown;
		}

		if (!player->IsValid()) {
			LG("offline_stall", "TM_OFFLINE_MODE: player not valid\n");
			return ReturnCode::OfflineMode::Unknown;
		}

		if (player->GetMainCha()->GetPlayer() != player) {
			LG("offline_stall", "TM_OFFLINE_MODE: player mismatch\n");
			return ReturnCode::OfflineMode::Unknown;
		}

		if (!g_Config.m_bOfflineStall) {
			LG("offline_stall", "TM_OFFLINE_MODE: offline stall disabled in config\n");
			return ReturnCode::OfflineMode::Disabled;
		}

		// Guard against double-creation (e.g. rapid button clicks)
		if (player->IsOfflineStallPending() || g_OfflineStallMgr.HasOfflineStall(player->GetDBChaId())) {
			LG("offline_stall", "TM_OFFLINE_MODE: stall already pending or exists for %s\n", player->GetMainCha()->GetName());
			return ReturnCode::OfflineMode::Unknown;
		}

		if (pCCha = player->GetCtrlCha(); !pCCha) {
			LG("offline_stall", "TM_OFFLINE_MODE: no ctrl cha\n");
			return ReturnCode::OfflineMode::Unknown;
		}

		if (!pCCha->IsLiveing()) {
			LG("offline_stall", "TM_OFFLINE_MODE: character dead\n");
			return ReturnCode::OfflineMode::Dead;
		}

		// Must be stalling to use offline mode
		if (!player->GetStallData()) {
			LG("offline_stall", "TM_OFFLINE_MODE: not stalling\n");
			return ReturnCode::OfflineMode::NotStalling;
		}

		if (auto map = pCCha->GetSubMap(); map && !map->CanSavePos()) {
			LG("offline_stall", "TM_OFFLINE_MODE: map refuses\n");
			return ReturnCode::OfflineMode::Refuse;
		}

		if (pCCha->IsBoat()) {
			LG("offline_stall", "TM_OFFLINE_MODE: on boat\n");
			return ReturnCode::OfflineMode::Refuse;
		}

		// Check if player is in a safe zone (non-combat area)
		if (!pCCha->IsInSafeArea()) {
			LG("offline_stall", "TM_OFFLINE_MODE: not in safe area\n");
			return ReturnCode::OfflineMode::NotSafeZone;
		}

		LG("offline_stall", "TM_OFFLINE_MODE: all checks passed\n");
		return ReturnCode::OfflineMode::Success;
	}();

	if (return_code != ReturnCode::OfflineMode::Success) {
		wpk.WriteChar(static_cast<uint8_t>(return_code));
		return wpk;
	}

	// Create the offline stall NPC
	if (g_OfflineStallMgr.CreateOfflineStall(player, pCCha)) {
		LG("offline_stall", "Created offline stall for %s via Offline Mode button\n", pCCha->GetName());
	} else {
		LG("offline_stall", "Failed to create offline stall for %s\n", pCCha->GetName());
		wpk.WriteChar(static_cast<uint8_t>(ReturnCode::OfflineMode::Unknown));
		return wpk;
	}

	g_pGameApp->CanReceiveRequests(player->GetID(), false); // Notify GroupServer
	player->SetCanReceiveRequests(false); // Set local GameServer flag
	
	// Mark the player for offline stall mode - they will be disconnected by GateServer
	// when it receives our success response. The virtual NPC will be spawned when the
	// player fully disconnects (detected by Update() polling in OfflineStallMgr).
	player->SetOfflineStallPending(true);
	
	// NOTE: We do NOT call KickPlayer2 here! The GateServer handles the disconnect
	// automatically after receiving our success response (see ToClient.cpp CMD_CM_OFFLINE_MODE).
	// Calling KickPlayer2 would cause a race condition with the GateServer's disconnect.
	
	LG("offline_stall", "Offline stall created for %s - GateServer will handle disconnect\n", pCCha->GetName());
	
	wpk.WriteChar(static_cast<uint8_t>(return_code));

	return wpk;
}

// 登录 GateServer
void GameServerApp::ConnectGate(GateServer* pGate) {
	T_B if (pGate->IsValid()) return;

	DataSocket* datasock = Connect(pGate->GetIP().c_str(), pGate->GetPort());
	if (datasock == nullptr) {
		// LG("Connect", "连接 GateServer 失败, ip = %s, port = %d.\n", pGate->GetIP().c_str(), pGate->GetPort() );
		LG("Connect", "connect to  GateServer failed, ip = %s, port = %d.\n", pGate->GetIP().c_str(), pGate->GetPort());
	} else {
		pGate->SetDataSock(datasock);
		datasock->SetPointer(pGate);
		// 通知应用层，连上一个 GateServer
		WPacket wpkt = GetWPacket();
		wpkt.WriteCmd(CMD_MM_GATE_CONNECT);
		wpkt.WriteChar(0);
		auto rpkt = RPacket(wpkt);
		AddPK(datasock, rpkt);
	}
	T_E
}

// 登录 InfoServer
bool GameServerApp::ConnectInfo(InfoServer* pInfo) {
	T_B
		// pInfo->StopInfoService();
		pInfo->RunInfoService(pInfo->GetIP().c_str(), pInfo->GetPort());
	return true;
	T_E
}

void GameServerApp::DisconnectInfo(InfoServer* pInfo) {
	T_B
		pInfo->StopInfoService();
	T_E
}

bool GameServerApp::IsValidGate(int i) {
	T_B if (i < 0 || i > m_gtnum) throw std::logic_error("gate index out of range!");

	return m_gtarray[i].IsValid();
	T_E
}

GateServer* GameServerApp::FindGate(char const* gt_name) {
	T_B for (int i = 0; i < m_gtnum; ++i) {
		if (m_gtarray[i].IsValid()) {
			if (m_gtarray[i].GetName().compare(gt_name) == 0)
				return &m_gtarray[i];
		}
	}

	return nullptr;
	T_E
}

//---------------------------------------------------------------------------
// Player Pointer Validation System
//---------------------------------------------------------------------------
std::atomic<uint32_t> GameServerApp::s_playerGeneration{1};

void GameServerApp::RegisterPlayer(GatePlayer* ply) {
	if (!ply) return;
	
	// Assign new generation
	uint32_t gen = s_playerGeneration.fetch_add(1, std::memory_order_relaxed);
	ply->SetGeneration(gen);
	
	std::unique_lock<std::shared_mutex> lock(m_playerRegistryMutex);
	uintptr_t addr = reinterpret_cast<uintptr_t>(ply);
	m_playerRegistry[addr] = gen;
	
	LG("PlayerRegistry", "GameServer: Registered player %p with generation %u (dbid=%u)\n", 
	   ply, gen, ply->GetDBChaId());
}

void GameServerApp::UnregisterPlayer(GatePlayer* ply) {
	if (!ply) return;
	
	std::unique_lock<std::shared_mutex> lock(m_playerRegistryMutex);
	uintptr_t addr = reinterpret_cast<uintptr_t>(ply);
	auto it = m_playerRegistry.find(addr);
	if (it != m_playerRegistry.end()) {
		LG("PlayerRegistry", "GameServer: Unregistered player %p (generation %u)\n", ply, it->second);
		m_playerRegistry.erase(it);
	}
}

bool GameServerApp::ValidatePlayerPointer(GatePlayer* ply, uintptr_t expectedGateAddr) {
	if (!ply) {
		return false;
	}
	
	uintptr_t addr = reinterpret_cast<uintptr_t>(ply);
	uint32_t expectedGeneration = 0;
	
	// Check registry
	{
		std::shared_lock<std::shared_mutex> lock(m_playerRegistryMutex);
		auto it = m_playerRegistry.find(addr);
		if (it == m_playerRegistry.end()) {
			LG("PlayerRegistry", "GameServer INVALID: Player %p not in registry\n", ply);
			return false;
		}
		expectedGeneration = it->second;
	}
	
	// Validate generation matches
	if (ply->GetGeneration() != expectedGeneration) {
		LG("PlayerRegistry", "GameServer INVALID: Player %p generation mismatch (expected %u, got %u)\n", 
		   ply, expectedGeneration, ply->GetGeneration());
		return false;
	}
	
	// Validate GateAddr if provided
	if (expectedGateAddr != 0 && ply->GetGateAddr() != expectedGateAddr) {
		LG("PlayerRegistry", "GameServer INVALID: Player %p gateAddr mismatch (expected %llu, got %llu)\n",
		   ply, (unsigned long long)expectedGateAddr, (unsigned long long)ply->GetGateAddr());
		return false;
	}
	
	return true;
}

bool GameServerApp::IsPlayerRegistered(GatePlayer* ply) const {
	if (!ply) return false;
	
	std::shared_lock<std::shared_mutex> lock(m_playerRegistryMutex);
	uintptr_t addr = reinterpret_cast<uintptr_t>(ply);
	return m_playerRegistry.find(addr) != m_playerRegistry.end();
}

// Player 相关
bool GameServerApp::AddPlayer(GatePlayer* gtplayer, GateServer* gt, uintptr_t gtaddr) {
	T_B if (gt == nullptr || gtplayer == nullptr) return false;
	if (!gt->IsValid())
		return false;
	if (gtplayer->Next || gtplayer->Prev) {
		// LG("玩家链表错误", "向链表插入玩家（dbid %u）时，发现其连接指针非空\n", gtplayer->GetDBChaId());
		LG("character list error ", "when insert character（dbid %u）to character ,find it connect pointer is not empty!\n", gtplayer->GetDBChaId());
		return false;
	}

	// 赋予 GatePlayer 某些字段值
	gtplayer->SetGate(gt);
	gtplayer->SetGateAddr(gtaddr);

	// Register in player registry with new generation
	RegisterPlayer(gtplayer);

	// 将 gtplayer 插入到头部
	gtplayer->Prev = nullptr;
	gtplayer->Next = gt->m_playerlist;

	if (gtplayer->Next != nullptr)
		gtplayer->Next->Prev = gtplayer;

	// 更新头部
	gt->m_playerlist = gtplayer;

	gt->AddPlayerCount();
	return true;
	T_E
}

bool GameServerApp::DelPlayer(GatePlayer* gtplayer) {
	T_B if (gtplayer == nullptr) return false;

	// Unregister from player registry before removal
	UnregisterPlayer(gtplayer);

	GateServer* gt = gtplayer->GetGate();
	if (gt == nullptr || !gt->IsValid())
		return false;

	if (gt->m_listcurplayer == gtplayer)
		gt->m_listcurplayer = gtplayer->Next;
	// 从链表中剔除
	if ((gtplayer->Prev == nullptr) && (gtplayer->Next == nullptr)) {
		if (gtplayer == gt->m_playerlist) { // 只有一个，清空
			gt->m_playerlist = nullptr;
		} else { // 非法的gtplayer
			return false;
		}
	} else if ((gtplayer->Prev == nullptr) && (gtplayer->Next != nullptr)) { // 头部
		if (gtplayer != gt->m_playerlist)
			return false;

		gt->m_playerlist = gtplayer->Next;
		gt->m_playerlist->Prev = nullptr;

		gtplayer->Next = nullptr;
	} else if ((gtplayer->Prev != nullptr) && (gtplayer->Next == nullptr)) { // 尾部
		gtplayer->Prev->Next = nullptr;

		gtplayer->Prev = nullptr;
	} else { // 中间
		gtplayer->Prev->Next = gtplayer->Next;
		gtplayer->Next->Prev = gtplayer->Prev;

		gtplayer->Prev = nullptr;
		gtplayer->Next = nullptr;
	}

	gt->DecPlayerCount();
	return true;
	T_E
}

bool GameServerApp::KickPlayer(GatePlayer* gtplayer, int lTimeSec) {
	T_B
		// WPacket pkt = GetWPacket();
		// pkt.WriteCmd(CMD_MT_KICKUSER);
		// pkt.WriteLong(lTimeSec);
		// return SendToClient(pkt, gtplayer);
		return KickPlayer2(gtplayer);
	T_E
}

bool GameServerApp::KickPlayer2(GatePlayer* gtplayer) {
	T_B
		WPacket pkt = GETWPACKET();
	pkt.WriteCmd(CMD_MT_KICKUSER);
	pkt.WriteLong(gtplayer->GetDBChaId());
	pkt.WriteLongLong(gtplayer->GetGateAddr());
	pkt.WriteShort(1);
	gtplayer->GetGate()->SendData(pkt);
	return true;
	T_E
}

bool GameServerApp::SendToGroup(WPacket& chginf) {
	GateServer* pGate;

	// 准备为每一个连接的 Gate 产生通知包
	for (int i = 0; i < m_gtnum; ++i) {
		pGate = &m_gtarray[i];

		if (pGate->IsValid()) {
			chginf.WriteShort(0);
			pGate->SendData(chginf);
			return true;
		}
	}
	return true;
}

// 特定发包接口
bool GameServerApp::SendToWorld(WPacket& chginf) {
	T_B
		WPacket CChginf;
	Short sCount;

	GatePlayer* pPlayer;
	GateServer* pGate;

	// 准备为每一个连接的 Gate 产生通知包
	for (int i = 0; i < m_gtnum; ++i) {
		pGate = &m_gtarray[i];

		if (pGate->IsValid()) {
			sCount = 0;
			CChginf = chginf.Duplicate();

			pPlayer = pGate->m_playerlist;
			while (pPlayer != nullptr) {
				CChginf.WriteLong(pPlayer->GetDBChaId());
				CChginf.WriteLongLong(pPlayer->GetGateAddr());
				sCount++;

				pPlayer = pPlayer->Next;
			}

			if (sCount > 0) {
				CChginf.WriteShort(sCount);
				pGate->SendData(CChginf);
			}
		}
	}

	return true;
	T_E
}

bool GameServerApp::SendToClient(GatePlayer* player, WPacket& pkt) {
	T_B if (player == nullptr) return false;

	GateServer* pGate = player->GetGate();
	if (pGate != nullptr) {
		pGate->SendData(pkt);
		return true;
	} else {
		return false;
	}
	T_E
}

bool GameServerApp::SendToClient(WPacket& pkt, GatePlayer* playerlist) {
	T_B if (playerlist == nullptr) return false;

	// 找出有效滴 Gate
	uShort usCount[MAX_GATE];
	WPacket CChginf[MAX_GATE];
	GateServer* pValidGate[MAX_GATE];
	Short sValidGateNum = 0;
	for (int i = 0; i < m_gtnum; ++i) {
		if (m_gtarray[i].IsValid()) {
			pValidGate[sValidGateNum] = &m_gtarray[i];
			usCount[sValidGateNum] = 0;
			CChginf[sValidGateNum] = pkt.Duplicate();
			sValidGateNum++;
		}
	}

	// 遍历 playerlist ，组织发往各个 Gate 的包
	GatePlayer* tmp = playerlist;
	while (tmp != nullptr) {
		if (tmp->GetGate() == nullptr) {
#ifdef defCOMMU_LOG
			LG("SendToClient", "WARNING! pGate = nullptr, cha_id=%d, gt_addr=0x%x\n",
			   tmp->GetDBChaId(), tmp->GetGateAddr());
#endif
		} else {
			for (int i = 0; i < sValidGateNum; ++i) {
				if (tmp->GetGate() == pValidGate[i]) {
					usCount[i]++;
					CChginf[i].WriteLong(tmp->GetDBChaId());
					CChginf[i].WriteLongLong(tmp->GetGateAddr());
					break;
				}
			}
		}

		tmp = tmp->GetNextPlayer();
	}

	// 　添加最后一个 个数 数据，并发送出去
	for (int i = 0; i < sValidGateNum; i++) {
		if (usCount[i] > 0) {
			CChginf[i].WriteShort(usCount[i]);
			pValidGate[i]->SendData(CChginf[i]);
		}
	}

	return true;
	T_E
}

bool GameServerApp::SendToClient(WPacket& pkt, int array_cnt, uplayer* uplayer_array) {
	T_B if (uplayer_array == nullptr) return false;

#ifdef defCOMMU_LOG
	// LG("SendToClient", "\nSendToClient called to notify %d players\n", array_cnt);
#endif

	// 找出有效滴 Gate
	uShort usCount[MAX_GATE];
	WPacket CChginf[MAX_GATE];
	GateServer* pValidGate[MAX_GATE];
	Short sValidGateNum = 0;
	for (int i = 0; i < m_gtnum; ++i) {
		if (m_gtarray[i].IsValid()) {
			pValidGate[sValidGateNum] = &m_gtarray[i];
#ifdef defCOMMU_LOG
			// LG("SendToClient", "Valid Gate 0x%x\n", pValidGate[sValidGateNum]);
#endif
			usCount[sValidGateNum] = 0;
			CChginf[sValidGateNum] = pkt.Duplicate();
			sValidGateNum++;
		}
	}
#ifdef defCOMMU_LOG
	// LG("SendToClient", "Valid Gate num = %d\n", sValidGateNum);
#endif

	// 遍历 uplayer_array ，组织发往各个 Gate 的包
	int j;
	for (int i = 0; i < array_cnt; ++i) {
#ifdef defCOMMU_LOG
		// LG("SendToClient", "cha_id = %d, pGate = 0x%x, gt_addr = 0x%x\n", uplayer_array[i].m_dwDBChaId, uplayer_array[i].pGate, uplayer_array[i].m_ulGateAddr);
#endif

		if (uplayer_array[i].pGate == nullptr) {
#ifdef defCOMMU_LOG
			LG("SendToClient", "WARNING! pGate = nullptr, cha_id=%d, gt_addr=0x%x\n",
			   uplayer_array[i].m_dwDBChaId, uplayer_array[i].m_ulGateAddr);
#endif
			continue;
		}

		for (j = 0; j < sValidGateNum; ++j) {
			if (uplayer_array[i].pGate == pValidGate[j]) {
				usCount[j]++;
				CChginf[j].WriteLong(uplayer_array[i].m_dwDBChaId);
				CChginf[j].WriteLongLong(uplayer_array[i].m_ulGateAddr);
				break;
			}
		}
	}

	// 　添加最后一个 个数 数据，并发送出去
	for (int i = 0; i < sValidGateNum; i++) {
#ifdef defCOMMU_LOG
		// LG("SendToClient", "send to Gate: %s for %d players\n", pValidGate[i]->GetIP().c_str(), usCount[i]);
#endif
		if (usCount[i] > 0) {
			CChginf[i].WriteShort(usCount[i]);
			pValidGate[i]->SendData(CChginf[i]);
		}
	}

	return true;
	T_E
}

bool GameServerApp::SendToGame(WPacket& pkt, uplayer* uplyr) {
	T_B return (uplyr->pGate->SendData(pkt) > 0) ? true : false;
	T_E
}

GameServerApp* g_gmsvr;

#endif
