/* Generated by Together */

#ifndef FRIEND_H
#define FRIEND_H
#include "Invitation.h"
// cChar	gc_standard_group[]="我的好友";
extern const cChar* gc_standard_group;

class Friend : public Invitation {
public:
	PtInviter FrndBeginInvited(Player* inviter) { return Invitation::BeginInvited(inviter); }
	PtInviter FrndEndInvited(Player* inviter) { return Invitation::EndInvited(inviter); }
	PtInviter FrndEndInvited(uLong cha_id) { return Invitation::EndInvited(cha_id); }
	Invited* FrndFindInvitedByInviterChaID(uLong cha_id) { return Invitation::FindInvitedByInviterChaID(cha_id); }

protected:
	Friend() {}
	~Friend() {}

private:
	virtual void FrndInvitedCheck(Invited* invited) = 0;
	int GetInvitedMax();
	void InvitedCheck(Invited* invited);

public:
	InterLockedLong m_CurrFriendNum;
};
#endif // FRIEND_H
