print("------------------------------------")
print("-- Loading hell file              --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_hell()
	return 199,941
end

function init_entry(map)
	SetMapEntryMapName(map, "jialebi")
	SetMapEntryTime(map, "2005/8/30/15/0", "1/0/0", "0/1/0", "0/6/0")
end

function after_enter_hell(role, map_copy)
	SystemNotice(role, "Mysterious Voice: "..GetChaDefaultName(role)..", you have invaded my realm of death, my pets will rip you apart mercilessly!") 
end

function before_leave_hell(role)
end

function map_copy_first_run_hell(map_copy)
end

function map_copy_run_hell(map_copy)
	for i = 5, 8, 1 do
		if Abaddon.Boss[i].Check == 0 then
			Abaddon.Boss[i].Role = CreateCha(Abaddon.Boss[i].ID, Abaddon.Boss[i].X, Abaddon.Boss[i].Y, 145, Abaddon.Boss[i].Life)
			Abaddon.Boss[i].Check = 1
		end
		if Abaddon.Boss[i].Check == 1 and CheckMonsterDead(Abaddon.Boss[i].Role) == 1 then
			Abaddon.Boss[i].Check = 2
			Abaddon.Tick = Abaddon.Tick + 1
			MapCopyNotice(map_copy, Abaddon.Boss[i].Message)
		end
	end
	if Abaddon.Tick == 8 then
		if Abaddon.Time[5] == 0 then
			MapCopyNotice(map_copy, "Warning: [Abaddon 5 - 8] has collapsed!")
			CloseMapEntry("hell")
			CloseMapCopy("hell")
		elseif Abaddon.Time[5] <= 15 then
			MapCopyNotice(map_copy, "Warning: [Abaddon 5 - 8] will collapse in "..Abaddon.Time[5].." second(s)!")
		elseif Abaddon.Time[5] == 300 then
			MapCopyNotice(map_copy, "Mysterious Voice: Do not let the defeat of my 4 pets get to your head. Their sacrifice will not be in vain! Prepare as the earth beneath your feet will vanish!")
		elseif(Abaddon.Time[5] - math.floor(Abaddon.Time[5]/60)*60) == 0 and Abaddon.Time[5] <= 300 then
			MapCopyNotice(map_copy, "Warning: [Abaddon 5 - 8] will collapse in "..(Abaddon.Time[5]/60).." minute(s)!")
		end
		Abaddon.Time[5] = Abaddon.Time[5] - 1
	end
end

function map_copy_run_special_hell(map)
end

function map_run_hell(map)
end

function map_copy_close_hell(map_copy)
	ClearAllSubMapCha(map_copy)
	ClearAllSubMapMonster(map_copy)
end

function map_copy_before_close_heilong(map_copy)
end

function can_open_entry_hell(map)
	local Week = tonumber(os.date("%w"))
	local Hour = tonumber(os.date("%H"))
	if Week == 6 or Week == 0 then
		if Hour == 15 then
			return 1
		end
	end
	return 0
end