print("------------------------------------")
print("-- Loading hell5 file             --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_hell5()
	return 55,33
end

function init_entry(map)
	SetMapEntryMapName(map, "hell4")
	SetMapEntryTime(map, "2007/1/20/0/30", "1/0/0", "0/2/0", "0/2/30")
end

function after_enter_hell5(Player, map_copy)
	SystemNotice(Player, "Mysterious Voice: "..GetChaDefaultName(Player)..", come and join me. I'm hoping to see what a human can grow to become!") 
end

function before_leave_hell5(Player)
end

function map_copy_first_run_hell5(map_copy)
end

function map_copy_run_hell5(map_copy)
	if Abaddon.Boss[19].Check == 1 then
		local PosX, PosY = GetChaPos(Abaddon.Boss[19].Role)
		for a = 1, #Abaddon.AbyssSkill, 1 do
			if (GetChaAttr(Abaddon.Boss[19].Role, ATTR_HP)/GetChaAttr(Abaddon.Boss[19].Role, ATTR_MXHP)) < Abaddon.AbyssSkill[a].Percentage and Abaddon.Boss[19].Skill[1] == Abaddon.AbyssSkill[a].Skill then
				CreateCha(Abaddon.AbyssSkill[a].ID, PosX, PosY, 295, 3600)
				MapCopyNotice(map_copy, Abaddon.AbyssSkill[a].Message)
				Abaddon.Boss[19].Skill[1] = Abaddon.Boss[19].Skill[1] + 1
			end
		end
	end
	if Abaddon.Boss[19].Check == 0 then
		Abaddon.Boss[19].Role = CreateCha(Abaddon.Boss[19].ID, Abaddon.Boss[19].X, Abaddon.Boss[19].Y, 145, Abaddon.Boss[19].Life)
		Abaddon.Boss[19].Check = 1
	end
	if Abaddon.Boss[19].Check == 1 and CheckMonsterDead(Abaddon.Boss[19].Role) == 1 then
		Abaddon.Boss[19].Check = 2
		Abaddon.Tick = Abaddon.Tick + 1
		MapCopyNotice(map_copy, Abaddon.Boss[19].Message)
	end
	if Abaddon.Tick == 19 then
		if Abaddon.Time[19] == 0 then
			MapCopyNotice(map_copy, "Warning:[Eternal Abaddon] has collapsed!")
			CloseMapEntry("hell5")
			CloseMapCopy("hell5")
			Abaddon_Init()
		elseif Abaddon.Time[19] <= 15 then
			MapCopyNotice(map_copy, "Warning:[Eternal Abaddon] will collapse in "..Abaddon.Time[19].." second(s)!")
		elseif Abaddon.Time[19] == 60 then
			MapCopyNotice(map_copy, "Goddess: I cannot believe that you made it so far. When I left this world, much anguish amassed and turned into a evil clone of myself, which brought much misery upon humankind. I await a day whereby somebody can remove this clone from the world. ")
			MapCopyNotice(map_copy, "Goddess: I can finally leave here. Thank you. I will watch over you and we will meet again one day. Grow stronger!")
			MapCopyNotice(map_copy, "Goddess: Adventurer, as my mortal body disappears, this place will collapse. Leave while you can!")
		elseif(Abaddon.Time[19] - math.floor(Abaddon.Time[19]/60)*60) == 0 and Abaddon.Time[19] <= 60 then
			MapCopyNotice(map_copy, "Warning:[Eternal Abaddon] will collapse in "..(Abaddon.Time[19]/60).." minute(s)!")
		end
		Abaddon.Time[19] = Abaddon.Time[19] - 1
	end
end

function map_copy_run_special_hell5(map)
end

function map_run_hell5(map)
end

function map_copy_close_hell5(map_copy)
end

function map_copy_before_close_hell5(map_copy)
end

function can_open_entry_hell5(map)
	return 1
end