print("-- [Loading] NPC Script [08]")

bgtalk1_1 = "I am Event NPC - Pappa. You can check out available events here. If you are interested, select the event for more detail or visit our website at: http://www.piratekingonline.com/"
bganswer1_13 = "Pirate King Online New Year Race"
bganswer1_14 = "Pirate's Day"
bganswer1_15 = "Distinguished family of the pirates"
bganswer1_16 = "Survey of Pirate King Online. To see which group of player you belong to"
bganswer1_17 = "4 Slots, Black Dragon"

bgtalk13 = "0"
bgtalk14 = "Event is not released. Please check out the website for more details."
bgtalk15 = "Starting from 1st January, accumulate reputation points and you stand a chance to win Gem of Soul, Blacksmith Pliers, Refining Gems and other items from Argent's bar."
bgtalk16 = "http: //vote.hdwonline.moliyo.com/vote1/ Check for more details,"
bgtalk17 = "0"

function dina_talk08() 
 	Talk (1, "Weird Hat Seller: I heard that the hat refining system is now opened. It seems that I have struck gold this time. Hey, you guys, take your tume to select the perfect hat for yourselves. No hurry." ) 
 	Text (1, "Trade", BuyPage)
	InitTrade() 
	Other(2553) 
	Other(2583) 
	Other(2584) 
end
-- Resident - Auntie Susan (404,639)
function dream_talk01()
	Talk(1, "That Jack stole my meat last night. Tell him not to be so greedy!")
	AddNpcMission(6944) -- Lv55 Bracelet Quest
end
-- Resident - May (433,619)
function dream_talk02()
	Talk(1, "My wish is to become the prettiest girl alive, when that happen, call me Princess!")
end
-- Private - Whitely (454,590)
function dream_talk03()
	Talk(1, "Don't think I'm stupid because my name is Whitely, all crimals can't escape from my hawk eye.")
end
--Private - Goldy (454,602)
function dream_talk04()
	Talk(1, "I'm not the blacksmith from Argent City, I'm like transformer~")
end
-- Private - Solomon (327,596)
function dream_talk05()
	Talk(1, "If you're here to report, please dial 110, if you want to buy me a drink, I've yet to knock off.")
end
-- Private - Maesomom (327,603)
function dream_talk06()
	Talk(1, "What matter do you have with me?")
end
-- Private - Hawong (342,558)
function dream_talk07()
	Talk(1, "What matter do you have with our lord?")
end
-- Private - Hachoi (348,559)
function dream_talk08()
	Talk(1,"My lord is busy, please do not disturb.")
end
-- Dream City Captain - Haagen Dazs (407,538)
function dream_talk09()
	Talk(1, "Wang Xiao Hu is troubling me, do you have any idea?")
end
-- Banker - Lovely (346,588)
function dream_talk10()
	Talk(1, "Lovely: Hi, I am the banker Lovely.")
	InitTrigger()
	TriggerCondition(1, HasMoney, 200)
	TriggerAction(1, TakeMoney, 200)
	TriggerAction(1, OpenBank)
	TriggerFailure(1, JumpPage, 2)
	Text(1, "Bank (Per 200g)", MultiTrigger, GetMultiTrigger(), 1)
	Talk(2, "Sorry, but you don't have enough gold.")
end
-- Banker - Abbey (437,606)
function dream_talk11()
	Talk(1, "Abby: Hi, I am the banker Abby.")
	InitTrigger()
	TriggerCondition(1, HasMoney, 200)
	TriggerAction(1, TakeMoney, 200)
	TriggerAction(1, OpenBank)
	TriggerFailure(1, JumpPage, 2)
	Text(1, "Bank (Per 200g)", MultiTrigger, GetMultiTrigger(), 1)
	Talk(2, "Sorry, but you don't have enough gold.")
end
-- Mysterious Loner - Xiaoxun (367,506)
function dream_talk12()
	Talk(1, "Oh who can tell me what is love in this world?")
end
-- Millionaire - Sheep (366,568)
function dream_talk13()
	Talk(1, "You know why the properties value raises so much? Hehe it's because of me.")
	AddNpcMission(6948) -- Lv65 Handguard Quest
end
-- Teleporter - Shiyazhi (343,640)
function dream_talk14()
	Talk(1, "Hello, ello, llo, lo, this is echo you know? I'm the smug teleporter, you brought enough money?")
	Text(1, "Teleport to Forgotten Island", Teleport, "Forgotten Island")
	Text(1, "Teleport to Argent City", Teleport, "Argent City")
	Text(1, "Teleport to Shaitan City", Teleport, "Shaitan City")
	Text(1, "Teleport to Icicle City", Teleport, "Icicle Castle")
	Text(1, "Record Respawn Point", JumpPage, 2 )
	Text(1, "Nothing, just looking around",CloseTalk)

	Talk(2, "Marian: Record Respawn Point at Dream Island?")
	Text(2, "Yes, please record", SetSpawnPos, "Dream Island")
	Text(2, "No, nevermind",CloseTalk)

end
-- Teleporter - Feifei (412,658)
function dream_talk15()
	Talk(1, "Port port port! BIU")
	Text(1, "Teleport to Region of the Demons!", Teleport, "Region of Demons")
	Text(1, "Teleport to Argent City", Teleport, "Argent City")
	Text(1, "Teleport to Shaitan City", Teleport, "Shaitan City")
	Text(1, "Teleport to Icicle City", Teleport, "Icicle Castle")
	Text(1, "Record Respawn Point", JumpPage, 2)
	Text(1, "Nothing, just looking around", CloseTalk)

	Talk( 2, "Marian: Record Respawn Point at Dream Island?" )
	Text( 2, "Yes, please record", SetSpawnPos, "Dream Island" )
	Text( 2, "No, nevermind", CloseTalk)
end
-- Teleporter - Huihui (435,547)
function dream_talk16()
	Talk(1, "Port port port! BIU")
	Text(1, "Teleport to Argent City", Teleport, "Argent City")
	Text(1, "Teleport to Shaitan City", Teleport, "Shaitan City")
	Text(1, "Teleport to Icicle City", Teleport, "Icicle Castle")
	Text(1, "Record Respawn Point", JumpPage, 2)
	Text(1, "Nothing, just looking around", CloseTalk)

	Talk( 2, "Marian: Record Respawn Point at Dream Island?")
	Text( 2, "Yes, please record", SetSpawnPos, "Dream Island")
	Text( 2, "No, nevermind",CloseTalk )
end
-- Teleporter - Xiuxiu (366,534)
function dream_talk17()
	Talk(1, "Port port port! BIU")
	Text(1, "Teleport to Argent City", Teleport, "Argent City")
	Text(1, "Teleport to Shaitan City", Teleport, "Shaitan City")
	Text(1, "Teleport to Icicle City", Teleport, "Icicle City")
	Text(1, "Record Respawn Point", JumpPage, 2)
	Text(1, "Nothing, just looking around", CloseTalk)

	Talk(2, "Marian: Record Respawn Point at Dream Island?")
	Text(2, "Yes, please record", SetSpawnPos, "Dream Island")
	Text(2, "No, nevermind",CloseTalk)
end
-- Event NPC - Jingle (379,599)
function dream_talk18()
	Talk(1, "Hello, I am Jingle, many have the same name as me")
	AddNpcMission(6890) -- Capture the fearsome Wang Xiao Hu
end
-- Physician - Strong (392,550)
function dream_talk19()
	Talk(1, "My wish is to heal, so, you need the medicine?")
	Text(1, "Trade", BuyPage)
	Text(1, "Combine", OpenUnite)
	Text(1, "Nothing, just looking around",CloseTalk)

	InitTrade()
	Other(3206)
	Other(3208)
	Other(3205)
	Other(3242)
	Other(3210)
	Other(3207)
	Other(3211)
	Other(3215)
	Other(3212)
	Other(3209)
	Other(3220)
	Other(3222)
	Other(3219)
	Other(3218)
	Other(3216)
	Other(3223)
	Other(3217)
	Other(3224)
	Other(3225)
	Other(3226)
	Other(3294)
	Other(3295)
	Other(3141)
	Other(4602)
	Other(4603)
	Other(4604)
	Other(3296)
	Other(886)
	Other(1611)
	Other(1682)
	Other(1842)
	Other(1612)
	Other(1710)
	Other(1693)
	Other(4716)
	Other(1716)
	Other(1711)
	Other(3384)
	Other(3932)
	Other(1619)
	Other(2396)
	Other(1729)
	Other(4459)
	Other(1697)
	Other(1730)
	Other(1712)
	Other(1734)
	Other(1621)
	Other(1703)
end
-- Hotel Owner - Whiskey (437,647)
function dream_talk20()
	Talk(1, "Lets get drunk tonight!")
end
-- Hotel Owner - Dust (437,658)
function dream_talk21()
	Talk(1, "Nothing worth more than a sip of beer.")
	AddNpcMission(6943) -- Lv55 Bracelet Quest
end
-- Flower Fairy JJ - Linger (308,537)
function dream_talk22()
	Talk(1, "You saw my sister Yuki? She got lost.")
end
-- Flower Fairy MM - Snowy (432,501)
function dream_talk23()
	Talk(1, "I miss my sister, but I did something unforgivable so I don\'t dare to see her.")
end
--Nurse - Blue (404,548)
function dream_talk24()
	InitTrigger()
	TriggerCondition( 1, LvCheck, "<", 40 )
	TriggerAction( 1, ReAll )
	TriggerCondition( 2, LvCheck, ">", 39 )
	TriggerCondition( 2, HasMoney, 20000 )
	TriggerAction( 2, TakeMoney, 20000 )
	TriggerAction( 2, ReAll )
	TriggerFailure( 2, JumpPage, 2 )
	Talk( 1, "Blue: Hi, I am the nurse Blue from the City of Sky. You can look for me if you are not feeling well. Lv40 and above have to pay a fee of 20000g." )
	Text( 1, "Greater Heal", MultiTrigger,GetMultiTrigger(),2)
	Talk( 2, "Blue: Sorry you do not have the gold..")

end
-- Resident - Olda (369,631)
function dream_talk25()
	Talk(1, "The seat will be mine eventually. Hehehe" )
	AddNpcMission(6942) -- Lv55 and Lv65 item starter quest
	AddNpcMission(6946) -- Lv65 Bracelet Quest
end
-- Resident - Uncle Jack (408,653)
function dream_talk26()
	Talk( 1, "Aunt Susan ask you to come right? I swear I never steal the meat!" )
end
-- Resident - Red-bearded Grandpa (390,652)
function dream_talk27()
	Talk(1, "Hihi, dear girl, come chat with grandpa")
	AddNpcMission(6945) -- Lv55 Handguard Quest
end
-- Resident - Depress (447,545)
function dream_talk28()
	Talk( 1, "Don't need to say anymore, his life is just 2 words, cough~ Hey don��t go, I haven't finish" )
end
-- Tools - Honor (426,565)
function dream_talk29()
	Talk( 1, "I have pride in selling items" )
end
-- Accessory - Twinkle
function dream_talk30()
	Talk(1, "I have got high class rings and necklace here, don��t worry about the price, we can talk about it later")
	Text(1, "Trade", BuyPage)

	InitTrade()
	Defence(4666)
	Defence(4667)
	Defence(4668)
	Defence(4669)
	Defence(4671)
	Defence(4672)
	Defence(4673)
	Defence(4674)
	Defence(4675)
	Defence(4676)
	Defence(4677)
	Defence(4678)
	Defence(4679)
	Defence(4681)
	Defence(4682)
	Defence(4683)
	Defence(4684)
	Defence(4685)
end
-- Tailor - Feifan (450,563)
function dream_talk31()
	Talk(1, "Come here and get what you don\'t from outside!")
end
-- Grocery - Bazhe (433,585)
function dream_talk32()
	Talk(1,"Hi, how can I help you?")
	Text(1, "Trade", BuyPage)
	Text(1, "Nothing, just looking around",CloseTalk)

	InitTrade()
	Other(1611)
	Other(1682)
	Other(1842)
	Other(1612)
	Other(1710)
	Other(1693)
	Other(4716)
	Other(1716)
	Other(1711)
	Other(3384)
	Other(3932)
	Other(1619)
	Other(2396)
	Other(1729)
	Other(4459)
	Other(1697)
	Other(1730)
	Other(1712)
	Other(1734)
	Other(1621)
	Other(1703)
end
-- Fruit Merchant - Linger (405,565)
function dream_talk33()
	Talk(1, "Today's special fruit -- Durian! Great for boy and girls!")
end
-- Armory Merchant - Perak (371,652)
function dream_talk34()
	Talk(1, "Hi, this is an armor and weapon shop.")
	Text(1, "Trade", BuyPage)
	Text(1, "Nothing, just looking around", CloseTalk)

	InitTrade()
	Weapon(0008)
	Weapon(0196)
	Weapon(0197)
	Weapon(0198)
	Weapon(0097)
	Weapon(0104)
	Weapon(0098)
	Weapon(0105)
	Weapon(0099)
	Weapon(0106)
	Weapon(0101)
	Weapon(0107)
	Weapon(0102)
	Weapon(0108)
	Weapon(0100)
	Weapon(4301)
	Weapon(0103)
	Weapon(4302)
	Weapon(1427)
	Weapon(1428)
	Weapon(1429)
	Weapon(1430)
	Weapon(1431)
	Weapon(1432)
	Weapon(1433)
	Weapon(1434)
	Weapon(1435)
	Weapon(1436)
	Weapon(1437)
	Weapon(1438)
	Weapon(1440)
	Weapon(1441)
	Weapon(1462)
	Weapon(1463)
	Weapon(1464)
	Weapon(1465)
	Weapon(1466)
	Weapon(1467)
	Weapon(1468)
	Weapon(1469)
	Weapon(1470)
	Weapon(1471)
	Weapon(1472)
	Weapon(1473)
	Weapon(1475)
	Weapon(1476)
	Weapon(0817)
	Weapon(0818)
	Weapon(0867)
	Weapon(0868)
	Weapon(0872)
	Weapon(0873)
	Weapon(0635)
	Weapon(0636)
end
-- Blacksmith - Uncle Jin (362,651)
function dream_talk35()
	Talk(1, "Hi, come find me if you want to upgrade or refine your gear.")
	Text(1, "Repair", OpenRepair)
	Text(1, "Forge", OpenForge)
	Text(1, "Fusion", OpenMilling)
	Text(1, "Apparel Fusion", OpenFusion)
	Text(1, "Apparel Upgrade", OpenUpgrade)
	Text(1, "You are too good!! I can't compare to you", CloseTalk)
end
-- City Leader - Alex (336,544)
function dream_talk36()
	Talk(1, "Haagen Daz said Wang Xiao Hu jail break. I am very worried")
	AddNpcMission(6947) -- Lv65 Bracelet Quest
end
-- Bar Waitress - Cuihua (435,634)
function dream_talk37()
	Talk(1, "Dear customer, we don\'t sell salty vegetables here.")
end
-- Beach Shop - Xiao Li (471,622)
function dream_talk38()
	Talk(1, "Hi, welcome. We have all the items from everywhere." )
	Text(1, "Trade", BuyPage )

	InitTrade()
	Other(3206)
	Other(3208)
	Other(3205)
	Other(3242)
	Other(3210)
	Other(3207)
	Other(3211)
	Other(3215)
	Other(3212)
	Other(3209)
	Other(3220)
	Other(3222)
	Other(3219)
	Other(3218)
	Other(3216)
	Other(3223)
	Other(3217)
	Other(3224)
	Other(3225)
	Other(3226)
	Other(3294)
	Other(3295)
	Other(3141)
	Other(4602)
	Other(4603)
	Other(4604)
	Other(3296)
	Other(886)
	Other(1611)
	Other(1682)
	Other(1842)
	Other(1612)
	Other(1710)
	Other(1693)
	Other(4716)
	Other(1716)
	Other(1711)
	Other(3384)
	Other(3932)
	Other(1619)
	Other(2396)
	Other(1729)
	Other(4459)
	Other(1697)
	Other(1730)
	Other(1712)
	Other(1734)
	Other(1621)
	Other(1703)
	Other(6613)
end
-- Teleporter - Junior You (652,281)
function dream_talk39()
	Talk(1, "Junior You: As long you come to me, I can teleport you to anywhere in Continent of Dreams.")
	Text(1, "Teleport to Dream Island", Teleport, "Dream Island")
	Text(1, "Teleport to Region of the Demons!", Teleport, "Region of Demons")
	Text(1, "Nothing, just looking around", CloseTalk)
end
-- Bard - Er Hao (669,110)
function dream_talk40()
    Talk(1, "Er Hao: I love to recite poem and go on a journey")
end
-- Teleporter - Rolan (250,154)
function dream_talk41()
	Talk(1, "Rolan: Hi, where do you want to go")
	Text(1, "Teleport to Dream Island", Teleport, "Dream Island")
	Text(1, "Teleport to Forgotten Island", Teleport, "Forgotten Island")
	Text(1, "Nothing, just looking around", CloseTalk )
end
-- Traveler - Nawei (157,253)
function dream_talk42()
    Talk(1, "Nawei: For safety purpose, always keep medicine with you!")
end
-- Demon Deacon - Sebastien (380,608)
function dream_talk43()
	Talk( 1 ,"Sebastien: Even being a member of the demon's royal family, my master is a very kind person~ Yes, my lord��.. I'm just a deacon.")
	Text( 1 , "I want to exchange Kiss of Demon" ,JumpPage , 2)
    Text( 1 , "I want to exchange Seal of Demon",JumpPage , 9)
	Text( 1 , "I want to exchange Shadow of Demon",JumpPage , 16)

	Talk( 2 ,"Master has finally arrange mission for me, I'm so excited~ I have to work hard on it!")
	Text( 2 , "I want to exchange Kiss of Demon (Crusader)",JumpPage , 3 )
	Text( 2 , "I want to exchange Kiss of Demon (Champion)",JumpPage , 4 )
	Text( 2 , "I want to exchange Kiss of Demon (Seal Master)",JumpPage , 5 )
	Text( 2 , "I want to exchange Kiss of Demon (Cleric)",JumpPage , 6 )
	Text( 2 , "I want to exchange Kiss of Demon (Sharpshooter)",JumpPage , 7 )
	Text( 2 , "I want to exchange Kiss of Demon (Voyager)",JumpPage , 8 )

	Talk( 3 ,"You need Demon voucher to exchange for Kiss of Demon (Crusader) Bracelet, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7380, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 3 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 3 , "Previous Page",JumpPage , 2 )

	Talk( 4 ,"You need Demon voucher to exchange for Kiss of Demon (Champion) Bracelet, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7382, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 4 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 4 , "Previous Page",JumpPage , 2 )

	Talk( 5 ,"You need Demon voucher to exchange for Kiss of Demon (Seal Master) Bracelet, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7384, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 5 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 5 , "Previous Page",JumpPage , 2 )

	Talk( 6 ,"You need Demon voucher to exchange for Kiss of Demon (Cleric) Bracelet, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7386, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 6 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 6 , "Previous Page",JumpPage , 2 )

	Talk( 7 ,"You need Demon voucher to exchange for Kiss of Demon (Sharpshooter) Bracelet, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7388, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 7 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 7 , "Previous Page",JumpPage , 2 )

	Talk( 8 ,"You need Demon voucher to exchange for Kiss of Demon (Voyager) Bracelet, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7390, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 8 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 8 , "Previous Page",JumpPage , 2 )

	Talk( 9 ,"Master has finally arrange mission for me, I'm so excited~ I have to work hard on it!")
	Text( 9 , "I want to exchange Seal of Demon (Crusader)",JumpPage , 10 )
	Text( 9 , "I want to exchange Seal of Demon (Champion)",JumpPage , 11 )
	Text( 9 , "I want to exchange Seal of Demon (Seal Master)",JumpPage , 12 )
	Text( 9 , "I want to exchange Seal of Demon (Cleric)",JumpPage , 13 )
	Text( 9 , "I want to exchange Seal of Demon (Sharpshooter)",JumpPage , 14 )
	Text( 9 , "I want to exchange Seal of Demon (Voyager)",JumpPage , 15 )

	Talk( 10 ,"You need Demon voucher to exchange for Seal of Demon (Crusader) Handguard, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7381, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 10 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 10 , "Previous Page",JumpPage , 9 )

	Talk( 11 ,"You need Demon voucher to exchange for Seal of Demon (Champion) Handguard, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7383, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 11 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 11 , "Previous Page",JumpPage , 9 )

	Talk( 12 ,"You need Demon voucher to exchange for Seal of Demon (Seal Master) Handguard, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7385, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 12 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 12 , "Previous Page",JumpPage , 9 )

	Talk( 13 ,"You need Demon voucher to exchange for Seal of Demon (Cleric) Handguard, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7387, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 13 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 13 , "Previous Page",JumpPage , 9 )

	Talk( 14 ,"You need Demon voucher to exchange for Seal of Demon (Sharpshooter) Handguard, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7389, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 14 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 14 , "Previous Page",JumpPage , 9 )

	Talk( 15 ,"You need Demon voucher to exchange for Seal of Demon (Voyager) Handguard, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7391, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 15 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 15 , "Previous Page",JumpPage , 9 )

	Talk( 16 ,"You need Demon voucher to exchange for Shadow of Demon Belt, are you sure you want to exchange?")
	InitTrigger()
	TriggerCondition( 1, HasItem, 7367, 1 )
	TriggerCondition(1, HasLeaveBagGrid, 1)
	TriggerCondition(1, KitbagLock, 0 )
 	TriggerAction( 1, TakeItem, 7367, 1 )
	TriggerAction( 1, GiveItem,7392, 1,4 )
	TriggerFailure( 1, JumpPage, 17 )
	Text( 16 , "Confirm",MultiTrigger, GetMultiTrigger(), 1 )
	Text( 16 , "Previous Page",JumpPage , 1 )

	Talk( 17 ,"Exchange failed. Please make sure you have the voucher and sufficient inventory slot.")
	Text( 17 ,"Return",JumpPage, 1)
end
dofile(GetResPath("../addons/_index.lua"))
dofile(GetResPath("script/shop/init.lua"))