print("--------------------------------------------------")
print("[**] Define Files [**]")
print("-- [Loading] ScriptDefine")

InitMap()
AddMap("garner", "Ascaron")
AddMap("magicsea", "Magical Ocean")
AddMap("darkblue", "Deep Blue")
AddMap("eastgoaf", "Eastern Goaf")
AddMap("lonetower", "Lone Tower")
AddMap("secretgarden", "Garden of Edel")
AddMap("darkswamp", "Dark Swamp")
AddMap("abandonedcity", "Forsaken City")
AddMap("abandonedcity2", "Forsaken City 2")
AddMap("abandonedcity3", "Forsaken City 3")
AddMap("puzzleworld", "Demonic World")
AddMap("puzzleworld2", "Demonic World 2")
AddMap("teampk", "Arena")
AddMap("jialebi", "Caribbean")
AddMap("garner2", "Chaos Argent")
AddMap("hell", "Abaddon 1")
AddMap("hell2", "Abaddon 2")
AddMap("hell3", "Abaddon 3")
AddMap("hell4", "Abaddon 4")
AddMap("hell5", "Abaddon 5")
AddMap("guildwar", "Sacred War")
AddMap("leiting2", "Thundoria Mirage")
AddMap("shalan2", "Shaitan Mirage")
AddMap("binglang2", "Icicle Mirage")
AddMap("guildwar2", "Mini Sacred War")
AddMap("yschurch", "Church")
AddMap("07xmas", "Chirstmas Village")
AddMap("07xmas2", "Converse Chirstmas Village")
AddMap("07xmas2", "Converse Chirstmas Village")
AddMap("PKmap", "PK Arena")
AddMap("DreamIsland", "Dream Island")
AddMap("starwalkway", "Starry Sky Alley")
AddMap("L4MAP", "L4MAP")
AddMap("heilong", "Black Dragon Lair")
AddMap("prisonisland", "Prison Island")
AddMap("winterland", "Winter Island")