/* Generated by Together */
#pragma once

#ifndef USE_IOCP

#include <string>
#include <atomic>
#include <shared_mutex>
#include <unordered_map>
#include "DBCCommon.h"
#include "PreAlloc.h"
#include "ThreadPool.h"
#include "CommRPC.h"
#include "Point.h"
#include "Identity.h"
#include "Usage.h"
#include "DataSocket.h"
#include "PacketQueue.h"
#include "Config.h"
#include "gtplayer.h"
#include "util.h"

#pragma pack(push, before_InfoNet)
#pragma pack(8)
#include "InfoNet.h"
#pragma pack(pop, before_InfoNet)

#include "MsgQueue.h"
using namespace dbc;
using namespace std;

// GateServer �����ṹ
class GameServerApp;
class GateServer {
public:
	GateServer() : m_pCDataSock(0), m_usPort(0), m_gtname(""), m_playerlist(nullptr), m_playercount(0) {
	}

	~GateServer() {
		m_pCDataSock = nullptr;
		m_gtname = "";
	}

	void SetDataSock(dbc::DataSocket* datasock) {
		m_pCDataSock = datasock;
	}

	void Invalid() {
		m_pCDataSock = nullptr;
	}

	bool IsValid() { return (m_pCDataSock != nullptr) ? true : false; }

	std::string& GetIP() { return m_strIp; }
	unsigned short& GetPort() { return m_usPort; }
	std::string& GetName() { return m_gtname; }
	// GatePlayer*& GetPlayerList() {return m_playerlist;}
	dbc::DataSocket* GetDataSock() const { return m_pCDataSock; }

	int SendData(dbc::WPacket pkt) {
		if (IsValid()) {
			return m_pCDataSock->SendData(pkt);
		} else {
			return 0;
		}
	}

	GatePlayer* m_listcurplayer; // ���ڱ�������

	// Player ˫����
	GatePlayer* m_playerlist;
	int m_playercount;
	void AddPlayerCount() { ++m_playercount; }
	void DecPlayerCount() { --m_playercount; }
	int GetPlayerCount() const { return m_playercount; }

protected:
	std::string m_strIp;
	unsigned short m_usPort;
	std::string m_gtname;

	dbc::DataSocket* m_pCDataSock;
};

// ���� GateServer ������
class ConnectGateServer : public dbc::Task {
public:
	ConnectGateServer(GameServerApp* gmsvr) {
		m_gmsvr = gmsvr;
		dwTimeOut = 3000;
	}

private:
	virtual int Process();
	DWORD dwTimeOut;
	GameServerApp* m_gmsvr;
};

// InfoServer��Ϣ����
class NetMessageQueue : public MsgQueue<pNetMessage> {
public:
	~NetMessageQueue() {
		Clear();
	}

	void Clear() {
		std::deque<pNetMessage>::iterator it;

		m_lock.lock();
		for (it = m_queue.begin(); it != m_queue.end(); it++) {
			FreeNetMessage(*it);
		}
		m_queue.clear();
		m_lock.unlock();
	}
};

// InfoServer������
class InfoServer : public InfoNetBase {
public:
	enum {
		CMD_FM_CONNECTED,	 // ����InfoServer
		CMD_FM_DISCONNECTED, // ��InfoServer�Ͽ�����
		CMD_FM_MSG,			 // InfoServer��������Ϣ

		CMD_INFO_MSG_MAX
	};

	InfoServer() : m_usPort(0), m_strIp(""), m_strPwd(""), bValid(false), m_nSection(0) {
	}

	~InfoServer() {
	}

	bool IsValid() { return bValid; }
	void SetValid() { bValid = true; }
	void InValid() { bValid = false; }

	std::string GetIP() { return m_strIp; }
	std::string GetPwd() { return m_strPwd; }
	unsigned short GetPort() { return m_usPort; }
	void SetInfoServer(std::string strIP, unsigned short usPort, std::string strPwd, int nSection) {
		if (usPort) {
			m_strIp = strIP;
			m_usPort = usPort;
			m_strPwd = strPwd;
			m_nSection = nSection;
		}
	}

	void Login();

	// ��InfoServer������Ϣ
	virtual bool SendData(pNetMessage msg) {
		bool bSend = false;
		msg->msgHead.msgSection = m_nSection;

		try {
			bSend = PostInfoSend(msg);
		} catch (...) {
			LG("Store_data", "SendData Error!\n");
		}

		return bSend;
	}

	// ȡ��Ϣ����
	virtual int PeekMsg(unsigned int ms);

	virtual void OnConnect(bool result);

	virtual void OnNetMessage(pNetMessage msg) {
		m_MsgQueue.Push(msg);
	}

	virtual void OnResend(pNetMessage msg) {
	}

	virtual void OnDisconnect();

protected:
	std::string m_strIp;
	unsigned short m_usPort;
	std::string m_strPwd;
	int m_nSection;
	bool bValid;
	NetMessageQueue m_MsgQueue;
};

// ���� InfoServer ������
class ToInfoServer : public dbc::Task {
public:
	ToInfoServer(GameServerApp* gmsvr) {
		m_gmsvr = gmsvr;
		m_dwTimeOut = 30000;
	}

private:
	virtual int Process();
	GameServerApp* m_gmsvr;
	DWORD m_dwTimeOut;
};

// ����ͨ��Ӧ����
class GameServerApp : public dbc::TcpClientApp, public dbc::RPCMGR, public dbc::PKQueue {
	friend class ConnectGateServer;
	friend class ToInfoServer;
	friend class InfoServer;

public:
	GameServerApp(dbc::ThreadPool* proc, dbc::ThreadPool* comm);
	virtual ~GameServerApp();

	// ��¼���
	char const* GetName() const { return m_strGameName.c_str(); }
	void ConnectGate(GateServer* pGate);
	bool IsValidGate(int i);
	GateServer* FindGate(char const* gt_name);

	bool ConnectInfo(InfoServer* pInfo);
	void DisconnectInfo(InfoServer* pInfo);
	InfoServer* GetInfoServer() { return &m_IfServer; }

	// Player ��� (GateServer����GatePlayer��һ��˫����)
	bool AddPlayer(GatePlayer* gtplayer, GateServer* gt, uintptr_t gtaddr);
	bool DelPlayer(GatePlayer* gtplayer);
	// add by xuedong
	bool BeginGetplayer(GateServer* gt);
	GatePlayer* const GetNextPlayer(GateServer* gt);

	void BeginGetGate(void);
	GateServer* GetNextGate(void);
	//

	bool KickPlayer(GatePlayer* gtplayer, int lTimeSec = 0);
	bool KickPlayer2(GatePlayer* gtplayer);

	// �ض������ӿ�
	bool SendToWorld(dbc::WPacket& pkt);
	bool SendToGroup(dbc::WPacket& chginf);
	bool SendToClient(GatePlayer* player, dbc::WPacket& pkt);
	bool SendToClient(dbc::WPacket& pkt, GatePlayer* playerlist);
	bool SendToClient(dbc::WPacket& pkt, int array_cnt, uplayer* uplayer_array);
	bool SendToGame(dbc::WPacket& pkt, uplayer* uplyr);

protected:
	virtual bool OnConnect(dbc::DataSocket* datasock);				  // ����ֵ:true-��������,false-����������
	virtual void OnDisconnect(dbc::DataSocket* datasock, int reason); // reasonֵ:0-���س��������˳���-3-���类�Է��رգ�-1-Socket����;-5-�����ȳ�������.
	virtual void OnProcessData(dbc::DataSocket* datasock, dbc::RPacket& recvbuf);
	void ProcessData(dbc::DataSocket* datasock, dbc::RPacket& recvbuf);

public:
	// SyncCall Handler
	virtual dbc::WPacket OnServeCall(dbc::DataSocket* datasock, dbc::RPacket& in_para);

	dbc::WPacket TM_KICKCHA(dbc::DataSocket* datasock, dbc::RPacket& pk);
	dbc::WPacket TM_OFFLINE_MODE(dbc::DataSocket* datasock, dbc::RPacket& pk);

	// ����InfoServer��Ϣ
	void ProcessData(pNetMessage msg, short sType);

	// Player pointer validation system
	static std::atomic<uint32_t> s_playerGeneration;
	mutable std::shared_mutex m_playerRegistryMutex;
	std::unordered_map<uintptr_t, uint32_t> m_playerRegistry;
	
	void RegisterPlayer(GatePlayer* ply);
	void UnregisterPlayer(GatePlayer* ply);
	bool ValidatePlayerPointer(GatePlayer* ply, uintptr_t expectedGateAddr = 0);
	bool IsPlayerRegistered(GatePlayer* ply) const;

public:
	int m_count;
	dbc::DataSocket* m_groupsock;
	Usage m_usage;

private:
	Mutex m_mutdisconn;

	GateServer m_gtarray[MAX_GATE];
	short m_gtnum;
	short m_listcurgt;

	InfoServer m_IfServer;

	std::string m_strGameName;
};

inline bool GameServerApp::BeginGetplayer(GateServer* gt) {
	if (gt == nullptr)
		return false;
	if (!gt->IsValid())
		return false;

	gt->m_listcurplayer = gt->m_playerlist;

	return true;
}

inline GatePlayer* const GameServerApp::GetNextPlayer(GateServer* gt) {
	GatePlayer* pretplayer = gt->m_listcurplayer;
	if (gt->m_listcurplayer)
		gt->m_listcurplayer = gt->m_listcurplayer->Next;

	return pretplayer;
}

inline void GameServerApp::BeginGetGate(void) {
	m_listcurgt = 0;
}

inline GateServer* GameServerApp::GetNextGate(void) {
	while (m_listcurgt < m_gtnum) {
		if (m_gtarray[m_listcurgt++].IsValid())
			return m_gtarray + (m_listcurgt - 1);
	}

	return 0;
}

extern GameServerApp* g_gmsvr;

inline void uplayer::Init(char const* gt_name, uintptr_t gt_addr, DWORD cha_id) {
	pGate = g_gmsvr->FindGate(gt_name);
	m_dwDBChaId = cha_id;
	m_ulGateAddr = gt_addr;
}

#endif
