print("------------------------------------")
print("-- Loading DreamIsland file       --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

dofile(GetResPath("DreamIsland/hook.lua"))

function dream_init()
	randomPos = {}
	randomPos[1] = {X = 45900, Y = 55600}
	randomPos[2] = {X = 9100, Y = 16000}
	randomPos[3] = {X = 59800, Y = 12500}
    randomNum = #randomPos
	thiefRound = {}
	thiefRound[1] = 0
	thiefRound[2] = 0
	thiefRound[3] = 0
end
dream_init()

function config(map)
	MapCanSavePos(map, 1)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_DreamIsland()
	return 0,0
end

function init_entry(map)
end

function after_enter_DreamIsland(Player, map_copy)
end

function before_leave_DreamIsland(Player)
end

function map_copy_first_run_DreamIsland(map_copy)
end

function map_copy_run_DreamIsland(map_copy)
	local Hour,Minute,Second = tonumber(os.date("%H")),tonumber(os.date("%M")),tonumber(os.date("%S"))
	local rand = math.random(1, randomNum)
	if Hour == 6 and Minute == 10 and Second == 0 then
		if thiefRound[1] == 0 then
			local CreateMob1 = CreateChaEx(1281, randomPos[rand].X, randomPos[rand].Y, 145, 60, map_copy)
			SetChaLifeTime(CreateMob1, 7200000)
			thiefRound[1] = 1
			GMNotice("<Dream Island Invasion>: Beware! "..GetChaDefaultName(CreateMob1).." at ["..math.floor(randomPos[rand].X/100)..","..math.floor(randomPos[rand].Y/100).."] Dream Island")
		end
	end
	if Hour == 14 and Minute == 10 and Second == 0 then
		if thiefRound[2] == 0 then
			local CreateMob2 = CreateChaEx(1281, randomPos[rand].X, randomPos[rand].Y, 145, 60, map_copy)
			SetChaLifeTime(CreateMob2, 7200000)
			thiefRound[2] = 1
			GMNotice("<Dream Island Invasion>: Beware! "..GetChaDefaultName(CreateMob2).." at ["..math.floor(randomPos[rand].X/100)..","..math.floor(randomPos[rand].Y/100).."] Dream Island")
		end
	end
	if Hour == 22 and Minute == 10 and Second == 0 then
		if thiefRound[3] == 0 then
			local CreateMob3 = CreateChaEx(1281, randomPos[rand].X, randomPos[rand].Y, 145, 60, map_copy)
			SetChaLifeTime(CreateMob3, 7200000)
			thiefRound[3] = 1
			GMNotice("<Dream Island Invasion>: Beware! "..GetChaDefaultName(CreateMob3).." at ["..math.floor(randomPos[rand].X/100)..","..math.floor(randomPos[rand].Y/100).."] Dream Island")
		end
	end
	if Hour == 0 and Minute == 0 and Second == 0 then
		dream_init()
	end
end

function map_copy_run_special_DreamIsland(map)
end

function map_run_DreamIsland(map)
end

function map_copy_close_DreamIsland(map_copy)
end

function map_copy_before_close_DreamIsland(map_copy)
end

function can_open_entry_DreamIsland(map)
	return 1
end